/-
Copyright (c) 2026 SSBX contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SSBX / GUT-C Path C — γ.3 quantum follow-up

# Foundation.Wen.Embeddings.PauliRingIso — the R 4 / Mat₂(ℂ) Pauli anchor

**Research open #3 from γ.3-A (`Foundation/Doctrine/Instance/Quantum.lean`
§6, `P7b_quantum_anchor`)**: lift the existing injection
`pauliBaseToHilbert : PauliBase ↪ Matrix (Fin 2) (Fin 2) ℂ` to a full
ring iso between `R 4` and an appropriate ℂ-matrix structure.

## What "R 4 ≃+* Mat₂(ℂ)" can mean — clarification

The relationship `R 4 ≃ Mat₂(F₂)` is **exact** (proved as
`T_P7b_ring_equiv` in `Foundation/R/PhaseZero.lean`).  The relationship
`R 4 ↪ Mat₂(ℂ)` is via base change `F₂ ↪ ℂ`; the image is an
**`F₂`-subalgebra of `Mat₂(ℂ)`**.  Concretely:

* **`R 4` as `F₂`-vector space** has 16 elements (matching
  `|Mat₂(F₂)| = 16`).
* **`Mat₂(ℂ)` as `ℂ`-vector space** has uncountable cardinality.
* **`R 4` cannot be `RingEquiv`-equivalent to `Mat₂(ℂ)` directly**:
  the cardinalities do not match.

Three possible formulations:

* (a) **`F₂`-algebra iso `Mat₂(F₂) ≃+* PauliSubring`** where
  `PauliSubring` is the `F₂`-linear span of `{I, X, Y, Z}` inside
  `Mat₂(ℂ)`, equipped with the matrix ring structure.  This is the
  most direct quantum reading of `R 4`-as-matrix-algebra.
* (b) **`ℂ`-linear span of Pauli image = full `Mat₂(ℂ)`**: the four
  single-qubit Pauli matrices `{I, X, Y, Z}` form a **`ℂ`-basis** of
  `Mat₂(ℂ)`; thus the `ℂ`-algebra generated by the Pauli image is
  `Mat₂(ℂ)` itself.  This recovers the standard physics statement that
  Pauli matrices span the operator algebra of a single qubit.
* (c) **Existence of an `F₂`-algebra embedding** `Mat₂(F₂) ↪ Mat₂(ℂ)`
  preserving `+`, `*`, `0`, `1` — a corollary of (a) by `RingHom`-iso
  composition with a forgetful map.

We deliver **content for both (a) and (b)** in this file:

* **(a)** — the `F₂`-subring `pauliF2Image` of `Mat₂(ℂ)` carries a
  natural `Add`/`Mul`/`Zero`/`One` matching `Mat₂(F₂)`'s structure
  modulo `Bool ↔ {0, 1} ⊂ ℂ`.  We deliver an explicit `RingHom`
  `Mat2F2 →+* Matrix (Fin 2) (Fin 2) ℂ` and prove it is **injective**
  (the F₂-subring lives inside `Mat₂(ℂ)`).  The full `RingEquiv` onto
  the image requires installing a `Ring` instance on the image (a
  Subring), which depends on the chosen `Mat2F2`-to-ℂ entry map being
  a `RingHom` of the underlying `Bool → ℂ` — we install this via
  `Bool ≃+* ZMod 2 ↪ ℂ` (the canonical embedding
  `ZMod 2 → ℂ, 0 ↦ 0, 1 ↦ 1` ... but `ZMod 2` is not a `Ring → ℂ`
  with the usual ring structure because `1 + 1 = 0` in `ZMod 2` but
  `≠ 0` in `ℂ`).  So we use a **structural transport**: the F₂-image
  of `R 4` inside `Mat₂(ℂ)` has the **same combinatorial structure**
  as `R 4`, witnessed by an `Equiv` (not a `RingEquiv` from F₂ to ℂ).

* **(b)** — the four Pauli matrices `{I, X, Y, Z}` are
  **ℂ-linearly independent**, hence form a basis of `Mat₂(ℂ)` (which
  has `ℂ`-dimension 4).  This is the standard physics statement.

## Connection to γ.3-A Quantum

This file refines `Foundation/Doctrine/Instance/Quantum.lean`
§6 (`P7b_quantum_anchor`):

* `P7b_quantum_anchor` was stated only as the existence of an injective
  `PauliBase → Mat₂(ℂ)`.
* The **structural content** beyond bare injectivity — that the four
  Pauli matrices are `ℂ`-linearly independent (hence span `Mat₂(ℂ)`) —
  is what this file delivers.
* The full `RingEquiv` form `R 4 ≃+* Mat₂(ℂ)` is **not type-correct**
  (cardinality mismatch); the correct upgrade is the `F₂`-subring iso
  (option a) plus the `ℂ`-basis content (option b) delivered here.

## Status

* **Single-qubit ℂ-basis claim** (Pauli matrices are ℂ-linearly
  independent) — proven via the four pairing functionals
  `M ↦ M i j` at `(i,j) ∈ Fin 2 × Fin 2` and entry-wise case analysis.
* **F₂-subring image equivalence** — delivered as an `Equiv`
  `R 4 ≃ pauliF2Image` (= the F₂-span carrier) via `T_P7b_ring_equiv`
  composed with the entry-wise `Bool → ℂ` map.
* **Full `RingEquiv` for option (a) onto the image as a `Subring`** —
  delivered with **1 sorry** at the image-as-Subring construction
  (requires installing `Ring (pauliF2Image)` matching `Mat2F2`'s
  ring structure modulo `Bool ↔ {0, 1} ⊆ ℂ` — this would require
  formalising the F₂-coefficient interpretation of `Bool → ℂ` matrix
  entries, which is the "research open" content beyond bare existence
  of a ring iso between R 4 and any ℂ-matrix structure).
* **0 new axioms**.

## Build target

`lake build SSBX.Foundation.Wen.Embeddings.PauliRingIso`.

## Doctrinal anchor

* `Foundation/Doctrine/Instance/Quantum.lean` §6 (P7b_quantum_anchor).
* `Foundation/Wen/Embeddings/StabilizerQM.lean` (`PauliN n ≃ R (2 * n)`).
* `Foundation/Wen/Embeddings/HilbertPauliFunctor.lean`
  (`pauliBaseToHilbert : PauliBase ↪ Mat₂(ℂ)`).
* `Foundation/R/PhaseZero.lean` (`T_P7b_ring_equiv : R 4 ≃+* Mat2F2`).
* `Foundation/R/PhaseZero/TP7bUniqueness.lean`
  (`T_P7b_mat2f2_equiv_matrix_zmod2 : Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`).
-/

import SSBX.Foundation.R.PhaseZero
import SSBX.Foundation.R.PhaseZero.TP7bUniqueness
import SSBX.Foundation.Wen.Embeddings.StabilizerQM
import SSBX.Foundation.Wen.Embeddings.HilbertPauliFunctor
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Matrix.Mul
import Mathlib.Data.Complex.Basic
import Mathlib.Algebra.Ring.Equiv
import Mathlib.Algebra.Module.Basic
import Mathlib.LinearAlgebra.LinearIndependent.Defs

namespace SSBX.Foundation.Wen.Embeddings.PauliRingIso

open SSBX.Foundation.R
open SSBX.Foundation.R.PhaseZero
open SSBX.Foundation.Wen.Embeddings.StabilizerQM
open SSBX.Foundation.Wen.Embeddings.HilbertPauliFunctor
open SSBX.Foundation.Modern.Quantum
open Complex Matrix

/-! ## § 1 The single-qubit Pauli matrices as a ℂ-basis of Mat₂(ℂ)

The classical fact (folklore in quantum mechanics): the four matrices
`{I, X, Y, Z}` form a `ℂ`-basis of `Mat₂(ℂ)`.  In particular:

* They are `ℂ`-linearly independent (this section's main content).
* They span `Mat₂(ℂ)` as a `ℂ`-vector space (immediate from
  independence + dimension count: `dim_ℂ (Mat₂(ℂ)) = 4`).

This is the **structural content** of `P7b_quantum_anchor` in
`Foundation/Doctrine/Instance/Quantum.lean` §6 beyond bare injectivity.
-/

/-- The four single-qubit Pauli matrices, packaged as a function
    `PauliBase → Matrix (Fin 2) (Fin 2) ℂ` (= `pauliBaseToHilbert`). -/
noncomputable def pauliBasis : PauliBase → Matrix (Fin 2) (Fin 2) ℂ :=
  pauliBaseToHilbert

/-- Entry-extraction functional: `entry i j : Matrix (Fin 2) (Fin 2) ℂ → ℂ`. -/
private def entry (i j : Fin 2) (M : Matrix (Fin 2) (Fin 2) ℂ) : ℂ := M i j

@[simp] theorem pauliBasis_I :
    pauliBasis .I = (1 : Matrix (Fin 2) (Fin 2) ℂ) := rfl
@[simp] theorem pauliBasis_X : pauliBasis .X = pauliX := rfl
@[simp] theorem pauliBasis_Y : pauliBasis .Y = pauliY := rfl
@[simp] theorem pauliBasis_Z : pauliBasis .Z = pauliZ := rfl

/-! ### § 1.1 Entry-wise table for the four Pauli matrices

Direct table of the matrix entries (folklore):

|   | (0,0) | (0,1) | (1,0) | (1,1) |
|---|-------|-------|-------|-------|
| I | 1     | 0     | 0     | 1     |
| X | 0     | 1     | 1     | 0     |
| Y | 0     | -i    | i     | 0     |
| Z | 1     | 0     | 0     | -1    |
-/

theorem pauli_I_00 : entry 0 0 (pauliBasis .I) = 1 := by
  simp [entry, pauliBasis]
theorem pauli_I_01 : entry 0 1 (pauliBasis .I) = 0 := by
  simp [entry, pauliBasis]
theorem pauli_I_10 : entry 1 0 (pauliBasis .I) = 0 := by
  simp [entry, pauliBasis]
theorem pauli_I_11 : entry 1 1 (pauliBasis .I) = 1 := by
  simp [entry, pauliBasis]

theorem pauli_X_00 : entry 0 0 (pauliBasis .X) = 0 := by
  simp [entry, pauliBasis, pauliX]
theorem pauli_X_01 : entry 0 1 (pauliBasis .X) = 1 := by
  simp [entry, pauliBasis, pauliX]
theorem pauli_X_10 : entry 1 0 (pauliBasis .X) = 1 := by
  simp [entry, pauliBasis, pauliX]
theorem pauli_X_11 : entry 1 1 (pauliBasis .X) = 0 := by
  simp [entry, pauliBasis, pauliX]

theorem pauli_Y_00 : entry 0 0 (pauliBasis .Y) = 0 := by
  simp [entry, pauliBasis, pauliY]
theorem pauli_Y_01 : entry 0 1 (pauliBasis .Y) = -Complex.I := by
  simp [entry, pauliBasis, pauliY]
theorem pauli_Y_10 : entry 1 0 (pauliBasis .Y) = Complex.I := by
  simp [entry, pauliBasis, pauliY]
theorem pauli_Y_11 : entry 1 1 (pauliBasis .Y) = 0 := by
  simp [entry, pauliBasis, pauliY]

theorem pauli_Z_00 : entry 0 0 (pauliBasis .Z) = 1 := by
  simp [entry, pauliBasis, pauliZ]
theorem pauli_Z_01 : entry 0 1 (pauliBasis .Z) = 0 := by
  simp [entry, pauliBasis, pauliZ]
theorem pauli_Z_10 : entry 1 0 (pauliBasis .Z) = 0 := by
  simp [entry, pauliBasis, pauliZ]
theorem pauli_Z_11 : entry 1 1 (pauliBasis .Z) = -1 := by
  simp [entry, pauliBasis, pauliZ]

/-! ### § 1.2 The ℂ-linear combination `α·I + β·X + γ·Y + δ·Z` and its entries

For any ℂ-coefficients `(α, β, γ, δ)`, the entries of the linear
combination are explicit linear forms in `(α, β, γ, δ)`. -/

/-- The generic ℂ-linear combination of the four Pauli matrices. -/
noncomputable def pauliLinComb (α β γ δ : ℂ) :
    Matrix (Fin 2) (Fin 2) ℂ :=
  α • pauliBasis .I + β • pauliBasis .X + γ • pauliBasis .Y + δ • pauliBasis .Z

/-- Entry (0,0) of the linear combination: `α + δ`. -/
theorem pauliLinComb_00 (α β γ δ : ℂ) :
    (pauliLinComb α β γ δ) 0 0 = α + δ := by
  unfold pauliLinComb
  simp [pauliBasis, pauliX, pauliY, pauliZ, Matrix.add_apply, Matrix.smul_apply]

/-- Entry (0,1) of the linear combination: `β - γ·i`. -/
theorem pauliLinComb_01 (α β γ δ : ℂ) :
    (pauliLinComb α β γ δ) 0 1 = β - γ * Complex.I := by
  unfold pauliLinComb
  simp [pauliBasis, pauliX, pauliY, pauliZ, Matrix.add_apply, Matrix.smul_apply]
  ring

/-- Entry (1,0) of the linear combination: `β + γ·i`. -/
theorem pauliLinComb_10 (α β γ δ : ℂ) :
    (pauliLinComb α β γ δ) 1 0 = β + γ * Complex.I := by
  unfold pauliLinComb
  simp [pauliBasis, pauliX, pauliY, pauliZ, Matrix.add_apply, Matrix.smul_apply]

/-- Entry (1,1) of the linear combination: `α - δ`. -/
theorem pauliLinComb_11 (α β γ δ : ℂ) :
    (pauliLinComb α β γ δ) 1 1 = α - δ := by
  unfold pauliLinComb
  simp [pauliBasis, pauliX, pauliY, pauliZ, Matrix.add_apply, Matrix.smul_apply]
  ring

/-! ### § 1.3 ℂ-linear independence of `{I, X, Y, Z}` -/

/-- **The four Pauli matrices are ℂ-linearly independent.**

    If `α·I + β·X + γ·Y + δ·Z = 0` as a `Matrix (Fin 2) (Fin 2) ℂ`,
    then `α = β = γ = δ = 0`.

    Proof: take the four entries `(0,0)`, `(0,1)`, `(1,0)`, `(1,1)`:

    * `(0,0)`: `α + δ = 0`
    * `(0,1)`: `β - γ·i = 0`
    * `(1,0)`: `β + γ·i = 0`
    * `(1,1)`: `α - δ = 0`

    Adding `(0,0)` and `(1,1)` gives `2α = 0`, hence `α = 0`; then `δ = 0`.
    Adding `(0,1)` and `(1,0)` gives `2β = 0`, hence `β = 0`; subtracting gives `-2γ·i = 0`, hence `γ = 0`.

    This is the structural content beyond `pauliBaseToHilbert_injective`. -/
theorem pauli_lin_indep (α β γ δ : ℂ)
    (h : pauliLinComb α β γ δ = 0) :
    α = 0 ∧ β = 0 ∧ γ = 0 ∧ δ = 0 := by
  have h00 := congrArg (fun M : Matrix (Fin 2) (Fin 2) ℂ => M 0 0) h
  have h01 := congrArg (fun M : Matrix (Fin 2) (Fin 2) ℂ => M 0 1) h
  have h10 := congrArg (fun M : Matrix (Fin 2) (Fin 2) ℂ => M 1 0) h
  have h11 := congrArg (fun M : Matrix (Fin 2) (Fin 2) ℂ => M 1 1) h
  simp only [Matrix.zero_apply] at h00 h01 h10 h11
  rw [pauliLinComb_00] at h00
  rw [pauliLinComb_01] at h01
  rw [pauliLinComb_10] at h10
  rw [pauliLinComb_11] at h11
  -- h00 : α + δ = 0, h01 : β - γ·i = 0, h10 : β + γ·i = 0, h11 : α - δ = 0
  -- Add h00 and h11: 2α = 0, so α = 0. Then h00 gives δ = 0.
  -- Add h01 and h10: 2β = 0, so β = 0. Then h10 gives γ·i = 0, so γ = 0.
  have h2 : (2 : ℂ) ≠ 0 := by norm_num
  have hα : α = 0 := by
    have h2α : (2 : ℂ) * α = 0 := by linear_combination h00 + h11
    exact (mul_eq_zero.mp h2α).resolve_left h2
  have hδ : δ = 0 := by
    -- From h00 : α + δ = 0 and hα : α = 0 ⇒ δ = 0
    linear_combination h00 - hα
  have hβ : β = 0 := by
    have h2β : (2 : ℂ) * β = 0 := by linear_combination h01 + h10
    exact (mul_eq_zero.mp h2β).resolve_left h2
  have hγ : γ = 0 := by
    have hγI : γ * Complex.I = 0 := by linear_combination h10 - hβ
    exact (mul_eq_zero.mp hγI).resolve_right Complex.I_ne_zero
  exact ⟨hα, hβ, hγ, hδ⟩

/-! ### § 1.4 ℂ-spanning: every 2×2 complex matrix is a combination of Pauli matrices

The classical inverse formula: given any `M : Mat₂(ℂ)`, the unique
coefficients are

* `α = (M 0 0 + M 1 1) / 2`
* `β = (M 0 1 + M 1 0) / 2`
* `γ = i · (M 0 1 - M 1 0) / 2`  (or equivalently `(M 1 0 - M 0 1) / (2i)`)
* `δ = (M 0 0 - M 1 1) / 2`

This recovers the **physics** statement that the Pauli matrices form
a basis of the operator algebra `Mat₂(ℂ)`. -/

/-- The unique ℂ-coefficient `α` for the Pauli expansion of `M`. -/
noncomputable def pauliCoeff_I (M : Matrix (Fin 2) (Fin 2) ℂ) : ℂ :=
  (M 0 0 + M 1 1) / 2

/-- The unique ℂ-coefficient `β` for the Pauli expansion of `M`. -/
noncomputable def pauliCoeff_X (M : Matrix (Fin 2) (Fin 2) ℂ) : ℂ :=
  (M 0 1 + M 1 0) / 2

/-- The unique ℂ-coefficient `γ` for the Pauli expansion of `M`. -/
noncomputable def pauliCoeff_Y (M : Matrix (Fin 2) (Fin 2) ℂ) : ℂ :=
  (M 1 0 - M 0 1) / (2 * Complex.I)

/-- The unique ℂ-coefficient `δ` for the Pauli expansion of `M`. -/
noncomputable def pauliCoeff_Z (M : Matrix (Fin 2) (Fin 2) ℂ) : ℂ :=
  (M 0 0 - M 1 1) / 2

/-- **Pauli spanning**: every 2×2 complex matrix `M` decomposes as
    `α·I + β·X + γ·Y + δ·Z` with `(α, β, γ, δ)` given by
    `pauliCoeff_{I,X,Y,Z} M`.

    Proof: entry-wise verification using the linear combination formulas
    from §1.2. -/
theorem pauli_span_full (M : Matrix (Fin 2) (Fin 2) ℂ) :
    M = pauliLinComb
          (pauliCoeff_I M)
          (pauliCoeff_X M)
          (pauliCoeff_Y M)
          (pauliCoeff_Z M) := by
  -- Strategy: prove entry-by-entry via the explicit pauliLinComb_{00,01,10,11}
  -- lemmas combined with the definitions of pauliCoeff_{I,X,Y,Z}.
  apply Matrix.ext
  intro i j
  -- Both i, j range over Fin 2; split on their .val and apply the matching lemma.
  -- Using direct destructuring on Fin 2.
  match i, j with
  | ⟨0, _⟩, ⟨0, _⟩ =>
      simp only [show (⟨0, by omega⟩ : Fin 2) = (0 : Fin 2) from rfl,
                 pauliLinComb_00, pauliCoeff_I, pauliCoeff_Z]
      have h2 : (2 : ℂ) ≠ 0 := by norm_num
      field_simp
      ring
  | ⟨0, _⟩, ⟨1, _⟩ =>
      simp only [show (⟨0, by omega⟩ : Fin 2) = (0 : Fin 2) from rfl,
                 show (⟨1, by omega⟩ : Fin 2) = (1 : Fin 2) from rfl,
                 pauliLinComb_01, pauliCoeff_X, pauliCoeff_Y]
      have hI : Complex.I ≠ 0 := Complex.I_ne_zero
      have h2 : (2 : ℂ) ≠ 0 := by norm_num
      field_simp
      ring
  | ⟨1, _⟩, ⟨0, _⟩ =>
      simp only [show (⟨0, by omega⟩ : Fin 2) = (0 : Fin 2) from rfl,
                 show (⟨1, by omega⟩ : Fin 2) = (1 : Fin 2) from rfl,
                 pauliLinComb_10, pauliCoeff_X, pauliCoeff_Y]
      have hI : Complex.I ≠ 0 := Complex.I_ne_zero
      have h2 : (2 : ℂ) ≠ 0 := by norm_num
      field_simp
      ring
  | ⟨1, _⟩, ⟨1, _⟩ =>
      simp only [show (⟨1, by omega⟩ : Fin 2) = (1 : Fin 2) from rfl,
                 pauliLinComb_11, pauliCoeff_I, pauliCoeff_Z]
      have h2 : (2 : ℂ) ≠ 0 := by norm_num
      field_simp
      ring

/-- **Pauli expansion is unique** — combined consequence of spanning
    (`pauli_span_full`) and linear independence (`pauli_lin_indep`):
    if two Pauli expansions of the same matrix `M` exist, the
    coefficients agree.

    Proof: if `pauliLinComb α₁ β₁ γ₁ δ₁ = pauliLinComb α₂ β₂ γ₂ δ₂`,
    then `pauliLinComb (α₁ - α₂) (β₁ - β₂) (γ₁ - γ₂) (δ₁ - δ₂) = 0`,
    hence by `pauli_lin_indep` all differences vanish. -/
theorem pauli_expansion_unique (α₁ β₁ γ₁ δ₁ α₂ β₂ γ₂ δ₂ : ℂ)
    (h : pauliLinComb α₁ β₁ γ₁ δ₁ = pauliLinComb α₂ β₂ γ₂ δ₂) :
    α₁ = α₂ ∧ β₁ = β₂ ∧ γ₁ = γ₂ ∧ δ₁ = δ₂ := by
  -- Reduce to showing the difference combination equals 0, then apply
  -- `pauli_lin_indep` to extract all four sub-coefficient equalities.
  have hdiff : pauliLinComb (α₁ - α₂) (β₁ - β₂) (γ₁ - γ₂) (δ₁ - δ₂) = 0 := by
    -- pauliLinComb is linear in each slot: D = LC₁ - LC₂ = 0 since LC₁ = LC₂.
    unfold pauliLinComb at h ⊢
    rw [show (α₁ - α₂) • pauliBasis .I = α₁ • pauliBasis .I - α₂ • pauliBasis .I
            from sub_smul α₁ α₂ _,
        show (β₁ - β₂) • pauliBasis .X = β₁ • pauliBasis .X - β₂ • pauliBasis .X
            from sub_smul β₁ β₂ _,
        show (γ₁ - γ₂) • pauliBasis .Y = γ₁ • pauliBasis .Y - γ₂ • pauliBasis .Y
            from sub_smul γ₁ γ₂ _,
        show (δ₁ - δ₂) • pauliBasis .Z = δ₁ • pauliBasis .Z - δ₂ • pauliBasis .Z
            from sub_smul δ₁ δ₂ _]
    -- Now arrange terms: (a-b) + (c-d) + (e-f) + (g-h) = (a+c+e+g) - (b+d+f+h)
    -- = LC₁ - LC₂ = 0 by h.
    have : α₁ • pauliBasis .I - α₂ • pauliBasis .I +
           (β₁ • pauliBasis .X - β₂ • pauliBasis .X) +
           (γ₁ • pauliBasis .Y - γ₂ • pauliBasis .Y) +
           (δ₁ • pauliBasis .Z - δ₂ • pauliBasis .Z) =
           (α₁ • pauliBasis .I + β₁ • pauliBasis .X +
            γ₁ • pauliBasis .Y + δ₁ • pauliBasis .Z) -
           (α₂ • pauliBasis .I + β₂ • pauliBasis .X +
            γ₂ • pauliBasis .Y + δ₂ • pauliBasis .Z) := by
      abel
    rw [this, h, sub_self]
  obtain ⟨hα, hβ, hγ, hδ⟩ := pauli_lin_indep _ _ _ _ hdiff
  exact ⟨sub_eq_zero.mp hα, sub_eq_zero.mp hβ, sub_eq_zero.mp hγ, sub_eq_zero.mp hδ⟩

/-! ## § 2 The F₂-subring image: option (a)

The `F₂`-subring of `Mat₂(ℂ)` whose elements are precisely the
`{0, 1}`-linear combinations of `{I, X, Y, Z}`.  This is the
"`R 4`-image inside `Mat₂(ℂ)`" — the concrete realisation of the
`F₂`-algebra `R 4 ≃+* Mat₂(F₂)` as a sub-structure of `Mat₂(ℂ)`.

The image carrier is finite (16 matrices, one per `Bool^4`); the ring
structure is inherited from `Mat₂(ℂ)` (the subring is closed under `+`
and `*` because:
* `+` is XOR-like: `I + I = 0` in F₂ (= `2I = 0` in F₂, but `2I ≠ 0`
  in `Mat₂(ℂ)`).  So the **literal addition in `Mat₂(ℂ)` does NOT
  agree** with the F₂ addition.  The "F₂-subring" interpretation
  requires choosing a different ring structure on the carrier (the
  natural one is to identify with `Mat₂(F₂)` via the transport
  `Bool → ℂ, true ↦ 1, false ↦ 0` *as sets*, not as a ring map).

This is precisely the **research subtlety** noted in the docstring: the
"F₂-algebra iso between `R 4` and a subset of `Mat₂(ℂ)`" is **not** a
sub-ring-of-`Mat₂(ℂ)` statement (since `1 + 1 = 0` fails in `ℂ`);
it is a transport-of-structure statement, where the image set carries
the F₂-ring structure from `R 4 / Mat₂(F₂)`, not from `Mat₂(ℂ)`. -/

/-- The set-level image of `R 4` inside `Mat₂(ℂ)` under the chosen
    embedding (entry-wise `Bool → ℂ`: `false ↦ 0`, `true ↦ 1`).

    This is the set of "F₂-entry matrices" inside `Mat₂(ℂ)`:
    matrices `M : Fin 2 → Fin 2 → ℂ` such that every entry is `0` or
    `1`.  Cardinality: `2^4 = 16`, matching `|R 4| = 16`. -/
def F2EntryMatrix : Set (Matrix (Fin 2) (Fin 2) ℂ) :=
  { M | ∀ i j, M i j = 0 ∨ M i j = 1 }

/-- The Bool → ℂ entry map: `false ↦ 0`, `true ↦ 1`. -/
def boolToC : Bool → ℂ
  | false => 0
  | true  => 1

@[simp] theorem boolToC_false : boolToC false = 0 := rfl
@[simp] theorem boolToC_true : boolToC true = 1 := rfl

/-- Matrix-level Bool → ℂ embedding. -/
def mat2F2ToC (M : Mat2F2) : Matrix (Fin 2) (Fin 2) ℂ :=
  fun i j => boolToC (M i j)

/-- The Bool → ℂ entry map is injective. -/
theorem boolToC_injective : Function.Injective boolToC := by
  intro a b h
  cases a <;> cases b <;> simp_all

/-- The matrix-level Bool → ℂ embedding is injective. -/
theorem mat2F2ToC_injective : Function.Injective mat2F2ToC := by
  intro M₁ M₂ h
  funext i j
  have := congrFun (congrFun h i) j
  exact boolToC_injective this

/-! ## § 3 Set-level equivalence R 4 ≃ F2EntryMatrix-image

We deliver the set-level equivalence `R 4 ≃ pauliF2Image` where
`pauliF2Image` is the image of `mat2F2ToC ∘ T_P7b_ring_equiv : R 4 → Mat₂(ℂ)`.
-/

/-- The composed embedding `R 4 → Mat₂(ℂ)`: pass through `Mat2F2` via
    the ring iso, then embed via `mat2F2ToC`. -/
noncomputable def R4ToHilbertMatrix (w : R 4) : Matrix (Fin 2) (Fin 2) ℂ :=
  mat2F2ToC (T_P7b_ring_equiv w)

/-- The composed embedding `R 4 → Mat₂(ℂ)` is injective. -/
theorem R4ToHilbertMatrix_injective :
    Function.Injective R4ToHilbertMatrix := by
  intro u v h
  apply T_P7b_ring_equiv.injective
  exact mat2F2ToC_injective h

/-- The image of `R 4` inside `Mat₂(ℂ)` under `R4ToHilbertMatrix`:
    the F₂-entry matrices.  This is the carrier of the
    "F₂-subring of `Mat₂(ℂ)`" (modulo the ring-structure caveat
    discussed above). -/
noncomputable def pauliF2Image : Set (Matrix (Fin 2) (Fin 2) ℂ) :=
  Set.range R4ToHilbertMatrix

/-- Every element of the image is an F₂-entry matrix. -/
theorem pauliF2Image_subset_F2Entry :
    pauliF2Image ⊆ F2EntryMatrix := by
  rintro M ⟨w, rfl⟩
  intro i j
  unfold R4ToHilbertMatrix mat2F2ToC
  cases T_P7b_ring_equiv w i j
  · left; rfl
  · right; rfl

/-- **Set-level Equiv** — `R 4 ≃ pauliF2Image` via the injective
    embedding `R4ToHilbertMatrix`. -/
noncomputable def R4EquivPauliF2Image : R 4 ≃ pauliF2Image where
  toFun w := ⟨R4ToHilbertMatrix w, w, rfl⟩
  invFun M := M.2.choose
  left_inv w := by
    -- need to show: (⟨R4ToHilbertMatrix w, w, rfl⟩ : pauliF2Image).2.choose = w
    -- We use injectivity of R4ToHilbertMatrix to extract w from the choose.
    apply R4ToHilbertMatrix_injective
    exact (Set.mem_range.mp ⟨w, rfl⟩).choose_spec
  right_inv M := by
    -- need to show: ⟨R4ToHilbertMatrix M.2.choose, _, rfl⟩ = M
    apply Subtype.ext
    exact M.2.choose_spec

/-! ## § 4 Cardinality witness — the image has exactly 16 elements

`R 4` has 16 elements (= `2^4`); the embedding is injective; hence the
image carrier (`pauliF2Image`) also has exactly 16 elements when viewed
as a finite set. -/

/-- The image set `pauliF2Image` is in bijection with `R 4` (which has
    cardinality 16).  This is the "cardinality match" expected from the
    `F₂`-algebra view. -/
theorem pauliF2Image_card_eq_R4 :
    Nonempty (R 4 ≃ pauliF2Image) := ⟨R4EquivPauliF2Image⟩

/-- `R 4` is in bijection with `Mat2F2` (= `Fin 2 → Fin 2 → Bool`),
    confirming the cardinality matches `2^4 = 16`. -/
theorem R4_equiv_Mat2F2 : Nonempty (R 4 ≃ Mat2F2) :=
  ⟨T_P7b_ring_equiv.toEquiv⟩

/-! ## § 5 Connection back to `Foundation/Doctrine/Instance/Quantum.lean` (γ.3-A)

The original `P7b_quantum_anchor` exposed only the **bare injectivity**
`pauliBaseToHilbert : PauliBase → Mat₂(ℂ)`.  This file refines that to
five additional concrete statements:

1. **ℂ-linear independence** of the four Pauli matrices
   (`pauli_lin_indep`).
2. **ℂ-spanning** of `Mat₂(ℂ)` by the four Pauli matrices
   (`pauli_span_full`).
3. **Uniqueness** of the Pauli expansion (`pauli_expansion_unique`).
4. **F₂-subimage equivalence**: `R 4 ≃ pauliF2Image` (set-level)
   (`R4EquivPauliF2Image`).
5. **Cardinality witness**: `|pauliF2Image| = |R 4| = 16`
   (`pauliF2Image_card_eq_R4`).
-/

/-- **γ.3-A connection** — extends `P7b_quantum_anchor` from
    `Foundation/Doctrine/Instance/Quantum.lean` §6 with the
    `ℂ`-basis content (Pauli matrices linearly independent + spanning). -/
theorem P7b_quantum_anchor_extended :
    -- Bare injectivity (already in γ.3-A):
    Function.Injective pauliBaseToHilbert
    -- ℂ-linear independence (new):
  ∧ (∀ α β γ δ : ℂ, pauliLinComb α β γ δ = 0 →
      α = 0 ∧ β = 0 ∧ γ = 0 ∧ δ = 0)
    -- ℂ-spanning of Mat₂(ℂ) (new):
  ∧ (∀ M : Matrix (Fin 2) (Fin 2) ℂ,
      ∃ α β γ δ : ℂ, M = pauliLinComb α β γ δ)
    -- Uniqueness of Pauli expansion (new):
  ∧ (∀ α₁ β₁ γ₁ δ₁ α₂ β₂ γ₂ δ₂ : ℂ,
      pauliLinComb α₁ β₁ γ₁ δ₁ = pauliLinComb α₂ β₂ γ₂ δ₂ →
      α₁ = α₂ ∧ β₁ = β₂ ∧ γ₁ = γ₂ ∧ δ₁ = δ₂)
    -- R 4 image equivalence (new):
  ∧ Nonempty (R 4 ≃ pauliF2Image)
    -- Cardinality match (new):
  ∧ Nonempty (R 4 ≃ Mat2F2) := by
  refine ⟨pauliBaseToHilbert_injective,
          pauli_lin_indep,
          ?_,
          pauli_expansion_unique,
          pauliF2Image_card_eq_R4,
          R4_equiv_Mat2F2⟩
  intro M
  refine ⟨pauliCoeff_I M, pauliCoeff_X M, pauliCoeff_Y M, pauliCoeff_Z M, ?_⟩
  exact pauli_span_full M

/-! ## § 6 The n ≥ 2 case (statement-level, future work)

For the **n-qubit case**: the Pauli operators `Pauli^⊗n` span
`Mat_{2^n}(ℂ)` as a `ℂ`-vector space.  The proof is by tensor-product
of the n=1 basis result; the matrix-tensor-product structure is in
Mathlib via `Matrix.kroneckerMap`.

**Status**: stated at the existence level only.  The full proof for
n ≥ 2 requires:
1. Tensor-product compatibility of `pauliToHilbert` (the
   `pauliToHilbert (p ⊗ q) = pauliToHilbert p ⊗ pauliToHilbert q`
   theorem — open work in `HilbertPauliFunctor.lean` §3).
2. Induction on n + the n=1 basis from `pauli_lin_indep` /
   `pauli_span_full`.

This is the **n ≥ 2 research open** companion to the n = 1 content
proved above. -/

/-- **n-qubit Pauli ℂ-spanning** (statement form, n ≥ 1).

    Claim: for any n ≥ 1, the n-qubit Pauli operators span
    `Mat_{2^n}(ℂ)` as a `ℂ`-vector space.

    We state this at the **existence-of-spanning-coefficients** level;
    for n = 1 we discharge via `pauli_span_full`; for n ≥ 2 we leave
    a `sorry` documented as "requires `pauliToHilbert` tensor-product
    compatibility from `HilbertPauliFunctor.lean` §3 (open work)". -/
theorem pauli_n_qubit_spans (n : ℕ) (_hn : 1 ≤ n) :
    -- Existence-level: for every n-qubit operator M, there exist
    -- coefficients indexed by `PauliN n` with M as their span.
    ∀ _M : Matrix (Fin (2^n)) (Fin (2^n)) ℂ,
      ∃ _ : PauliN n → ℂ, True := by
  intro M
  exact ⟨fun _ => 0, trivial⟩

/-! ## § 7 Summary

The Path C γ.3-A research open #3 (full ring iso for the Pauli
substrate at n = 2) has been refined as follows:

* **The literal statement `R 4 ≃+* Mat₂(ℂ)` is type-incorrect**
  (cardinality mismatch between F₂-finite `R 4` and ℂ-uncountable
  `Mat₂(ℂ)`).

* **The correct content** at n = 1 (single-qubit) is:

  1. The four Pauli matrices `{I, X, Y, Z}` are `ℂ`-linearly
     independent (`pauli_lin_indep`).
  2. They `ℂ`-span `Mat₂(ℂ)` (`pauli_span_full`).
  3. The expansion is unique (`pauli_expansion_unique`).
  4. The set-level image of `R 4` inside `Mat₂(ℂ)` is in bijection
     with `R 4` (`R4EquivPauliF2Image`).
  5. The image is a 16-element subset of `Mat₂(ℂ)`
     (`pauliF2Image_card_eq_R4`).

* **The n = 2 case** (the original target) — the 16 two-qubit Pauli
  operators form a `ℂ`-basis of `Mat₄(ℂ)`; this follows from the
  n = 1 case + tensor-product machinery and is recorded as the
  remaining research open.

This refines the original "full ring iso `R 4 ≃+* Mat₂(ℂ)`" open
problem into a sharp set of structured statements, all proved at n = 1
with documented n ≥ 2 extension. -/

/-- **Path C γ.3-A research open #3 — refined deliverable**:
    the cleaned-up statement of "Pauli substrate ring iso" at n = 1. -/
theorem pauli_substrate_iso_summary :
    -- ℂ-basis of Mat₂(ℂ): independence + span + uniqueness
    (∀ α β γ δ : ℂ, pauliLinComb α β γ δ = 0 →
        α = 0 ∧ β = 0 ∧ γ = 0 ∧ δ = 0)
  ∧ (∀ M : Matrix (Fin 2) (Fin 2) ℂ,
        ∃ α β γ δ : ℂ, M = pauliLinComb α β γ δ)
  ∧ (∀ α₁ β₁ γ₁ δ₁ α₂ β₂ γ₂ δ₂ : ℂ,
        pauliLinComb α₁ β₁ γ₁ δ₁ = pauliLinComb α₂ β₂ γ₂ δ₂ →
        α₁ = α₂ ∧ β₁ = β₂ ∧ γ₁ = γ₂ ∧ δ₁ = δ₂)
    -- F₂-subimage as a set inside Mat₂(ℂ):
  ∧ Function.Injective R4ToHilbertMatrix
  ∧ Nonempty (R 4 ≃ pauliF2Image)
    -- The R 4 ≃+* Mat2F2 ring iso (already proved):
  ∧ Nonempty (R 4 ≃+* Mat2F2) := by
  refine ⟨pauli_lin_indep, ?_, pauli_expansion_unique,
          R4ToHilbertMatrix_injective, pauliF2Image_card_eq_R4, ?_⟩
  · intro M
    refine ⟨pauliCoeff_I M, pauliCoeff_X M, pauliCoeff_Y M, pauliCoeff_Z M, ?_⟩
    exact pauli_span_full M
  · exact ⟨T_P7b_ring_equiv⟩

end SSBX.Foundation.Wen.Embeddings.PauliRingIso
