import SSBX.Text.WenyanOperators.Audit.R
import SSBX.Text.WenyanOperators.Audit.C
import SSBX.Text.WenyanOperators.Audit.T
import SSBX.Text.WenyanOperators.Audit.F
import SSBX.Text.WenyanOperators.Audit.B
import SSBX.Text.WenyanOperators.Audit.Q
import SSBX.Text.WenyanOperators.Audit.K
import SSBX.Text.WenyanOperators.Audit.M
import SSBX.Text.WenyanOperators.Audit.N
import SSBX.Text.WenyanOperators.Audit.I
import SSBX.Text.WenyanOperators.Audit.S
import SSBX.Text.WenyanOperators.Audit.H
import SSBX.Text.WenyanOperators.Audit.P
import SSBX.Text.WenyanOperators.Audit.G
import SSBX.Text.WenyanOperators.Audit.A
import SSBX.Text.WenyanOperators.Audit.D
import SSBX.Text.WenyanOperators.Audit.E
import SSBX.Text.WenyanOperators.Audit.L
import SSBX.Text.WenyanOperators.Audit.Y
import SSBX.Text.WenyanOperators.Audit.X
import SSBX.Text.WenyanOperators.Audit.Z
import SSBX.Text.WenyanOperators.Audit.ZHU
import SSBX.Text.WenyanOperators.Audit.SUN
import SSBX.Text.WenyanOperators.Audit.CHU
import SSBX.Text.WenyanOperators.Audit.LIJ
import SSBX.Text.WenyanOperators.Audit.ZA

namespace SSBX.Text.WenyanOperators

theorem allOperatorIds_complete (id : OperatorId) : id ∈ allOperatorIds := by
  cases id
  · exact Audit.mem_R_1
  · exact Audit.mem_R_2
  · exact Audit.mem_R_3
  · exact Audit.mem_R_4
  · exact Audit.mem_R_5
  · exact Audit.mem_R_6
  · exact Audit.mem_R_7
  · exact Audit.mem_R_8
  · exact Audit.mem_R_9
  · exact Audit.mem_R_10
  · exact Audit.mem_R_11
  · exact Audit.mem_R_12
  · exact Audit.mem_R_13
  · exact Audit.mem_R_14
  · exact Audit.mem_R_15
  · exact Audit.mem_C_1
  · exact Audit.mem_C_2
  · exact Audit.mem_C_3
  · exact Audit.mem_C_4
  · exact Audit.mem_C_5
  · exact Audit.mem_C_6
  · exact Audit.mem_C_7
  · exact Audit.mem_C_8
  · exact Audit.mem_T_1
  · exact Audit.mem_T_2
  · exact Audit.mem_T_3
  · exact Audit.mem_T_4
  · exact Audit.mem_T_5
  · exact Audit.mem_T_6
  · exact Audit.mem_T_7
  · exact Audit.mem_T_8
  · exact Audit.mem_T_9
  · exact Audit.mem_T_10
  · exact Audit.mem_T_11
  · exact Audit.mem_T_12
  · exact Audit.mem_T_13
  · exact Audit.mem_T_14
  · exact Audit.mem_T_15
  · exact Audit.mem_F_1
  · exact Audit.mem_F_2
  · exact Audit.mem_F_3
  · exact Audit.mem_F_4
  · exact Audit.mem_F_5
  · exact Audit.mem_F_6
  · exact Audit.mem_F_7
  · exact Audit.mem_F_8
  · exact Audit.mem_F_9
  · exact Audit.mem_F_10
  · exact Audit.mem_F_11
  · exact Audit.mem_F_12
  · exact Audit.mem_B_1
  · exact Audit.mem_B_2
  · exact Audit.mem_B_3
  · exact Audit.mem_B_4
  · exact Audit.mem_B_5
  · exact Audit.mem_B_6
  · exact Audit.mem_B_7
  · exact Audit.mem_B_8
  · exact Audit.mem_Q_1
  · exact Audit.mem_Q_2
  · exact Audit.mem_Q_3
  · exact Audit.mem_Q_4
  · exact Audit.mem_Q_5
  · exact Audit.mem_Q_6
  · exact Audit.mem_Q_7
  · exact Audit.mem_Q_8
  · exact Audit.mem_K_1
  · exact Audit.mem_K_2
  · exact Audit.mem_K_3
  · exact Audit.mem_K_4
  · exact Audit.mem_K_5
  · exact Audit.mem_K_6
  · exact Audit.mem_K_7
  · exact Audit.mem_K_8
  · exact Audit.mem_M_1
  · exact Audit.mem_M_2
  · exact Audit.mem_M_3
  · exact Audit.mem_M_4
  · exact Audit.mem_M_5
  · exact Audit.mem_M_6
  · exact Audit.mem_M_7
  · exact Audit.mem_M_8
  · exact Audit.mem_N_1
  · exact Audit.mem_N_2
  · exact Audit.mem_N_3
  · exact Audit.mem_N_4
  · exact Audit.mem_N_5
  · exact Audit.mem_N_6
  · exact Audit.mem_N_7
  · exact Audit.mem_N_8
  · exact Audit.mem_I_1
  · exact Audit.mem_I_2
  · exact Audit.mem_I_3
  · exact Audit.mem_I_4
  · exact Audit.mem_I_5
  · exact Audit.mem_I_6
  · exact Audit.mem_I_7
  · exact Audit.mem_I_8
  · exact Audit.mem_I_9
  · exact Audit.mem_S_1
  · exact Audit.mem_S_2
  · exact Audit.mem_S_3
  · exact Audit.mem_S_4
  · exact Audit.mem_S_5
  · exact Audit.mem_S_6
  · exact Audit.mem_S_7
  · exact Audit.mem_S_8
  · exact Audit.mem_S_9
  · exact Audit.mem_S_10
  · exact Audit.mem_S_11
  · exact Audit.mem_S_12
  · exact Audit.mem_S_13
  · exact Audit.mem_S_14
  · exact Audit.mem_S_15
  · exact Audit.mem_S_16
  · exact Audit.mem_S_17
  · exact Audit.mem_S_18
  · exact Audit.mem_S_19
  · exact Audit.mem_S_20
  · exact Audit.mem_H_1
  · exact Audit.mem_H_2
  · exact Audit.mem_H_3
  · exact Audit.mem_H_4
  · exact Audit.mem_H_5
  · exact Audit.mem_H_6
  · exact Audit.mem_H_7
  · exact Audit.mem_H_8
  · exact Audit.mem_P_1
  · exact Audit.mem_P_2
  · exact Audit.mem_P_3
  · exact Audit.mem_P_4
  · exact Audit.mem_P_5
  · exact Audit.mem_P_6
  · exact Audit.mem_P_7
  · exact Audit.mem_P_8
  · exact Audit.mem_P_9
  · exact Audit.mem_P_10
  · exact Audit.mem_P_11
  · exact Audit.mem_P_12
  · exact Audit.mem_P_13
  · exact Audit.mem_P_14
  · exact Audit.mem_P_15
  · exact Audit.mem_P_16
  · exact Audit.mem_P_17
  · exact Audit.mem_P_18
  · exact Audit.mem_P_19
  · exact Audit.mem_P_20
  · exact Audit.mem_P_21
  · exact Audit.mem_P_22
  · exact Audit.mem_P_23
  · exact Audit.mem_P_24
  · exact Audit.mem_G_1
  · exact Audit.mem_G_2
  · exact Audit.mem_G_3
  · exact Audit.mem_G_4
  · exact Audit.mem_G_5
  · exact Audit.mem_G_6
  · exact Audit.mem_G_7
  · exact Audit.mem_G_8
  · exact Audit.mem_G_9
  · exact Audit.mem_G_10
  · exact Audit.mem_G_11
  · exact Audit.mem_A_1
  · exact Audit.mem_A_2
  · exact Audit.mem_A_3
  · exact Audit.mem_A_4
  · exact Audit.mem_A_5
  · exact Audit.mem_A_6
  · exact Audit.mem_A_7
  · exact Audit.mem_A_8
  · exact Audit.mem_A_9
  · exact Audit.mem_A_10
  · exact Audit.mem_A_11
  · exact Audit.mem_A_12
  · exact Audit.mem_A_13
  · exact Audit.mem_A_14
  · exact Audit.mem_A_15
  · exact Audit.mem_A_16
  · exact Audit.mem_A_17
  · exact Audit.mem_A_18
  · exact Audit.mem_A_19
  · exact Audit.mem_A_20
  · exact Audit.mem_D_1
  · exact Audit.mem_D_2
  · exact Audit.mem_D_3
  · exact Audit.mem_D_4
  · exact Audit.mem_D_5
  · exact Audit.mem_D_6
  · exact Audit.mem_D_7
  · exact Audit.mem_D_8
  · exact Audit.mem_D_9
  · exact Audit.mem_D_10
  · exact Audit.mem_E_1
  · exact Audit.mem_E_2
  · exact Audit.mem_E_3
  · exact Audit.mem_E_4
  · exact Audit.mem_E_5
  · exact Audit.mem_E_6
  · exact Audit.mem_E_7
  · exact Audit.mem_E_8
  · exact Audit.mem_E_9
  · exact Audit.mem_L_1
  · exact Audit.mem_L_2
  · exact Audit.mem_L_3
  · exact Audit.mem_L_4
  · exact Audit.mem_L_5
  · exact Audit.mem_L_6
  · exact Audit.mem_L_7
  · exact Audit.mem_L_8
  · exact Audit.mem_L_9
  · exact Audit.mem_L_10
  · exact Audit.mem_L_11
  · exact Audit.mem_L_12
  · exact Audit.mem_L_13
  · exact Audit.mem_L_14
  · exact Audit.mem_L_15
  · exact Audit.mem_L_16
  · exact Audit.mem_Y_1
  · exact Audit.mem_Y_2
  · exact Audit.mem_Y_3
  · exact Audit.mem_Y_4
  · exact Audit.mem_Y_5
  · exact Audit.mem_Y_6
  · exact Audit.mem_Y_7
  · exact Audit.mem_Y_8
  · exact Audit.mem_Y_9
  · exact Audit.mem_Y_10
  · exact Audit.mem_Y_11
  · exact Audit.mem_Y_12
  · exact Audit.mem_Y_13
  · exact Audit.mem_Y_14
  · exact Audit.mem_Y_15
  · exact Audit.mem_Y_16
  · exact Audit.mem_Y_17
  · exact Audit.mem_Y_18
  · exact Audit.mem_Y_19
  · exact Audit.mem_Y_20
  · exact Audit.mem_Y_21
  · exact Audit.mem_Y_22
  · exact Audit.mem_Y_23
  · exact Audit.mem_Y_24
  · exact Audit.mem_Y_25
  · exact Audit.mem_Y_26
  · exact Audit.mem_Y_27
  · exact Audit.mem_Y_28
  · exact Audit.mem_X_1
  · exact Audit.mem_X_2
  · exact Audit.mem_X_3
  · exact Audit.mem_X_4
  · exact Audit.mem_X_5
  · exact Audit.mem_X_6
  · exact Audit.mem_X_7
  · exact Audit.mem_X_8
  · exact Audit.mem_X_9
  · exact Audit.mem_X_10
  · exact Audit.mem_X_11
  · exact Audit.mem_X_12
  · exact Audit.mem_X_13
  · exact Audit.mem_X_14
  · exact Audit.mem_X_15
  · exact Audit.mem_X_16
  · exact Audit.mem_Z_1
  · exact Audit.mem_Z_2
  · exact Audit.mem_Z_3
  · exact Audit.mem_Z_4
  · exact Audit.mem_Z_5
  · exact Audit.mem_Z_6
  · exact Audit.mem_Z_7
  · exact Audit.mem_Z_8
  · exact Audit.mem_Z_9
  · exact Audit.mem_Z_10
  · exact Audit.mem_Z_11
  · exact Audit.mem_Z_12
  · exact Audit.mem_Z_13
  · exact Audit.mem_Z_14
  · exact Audit.mem_Z_15
  · exact Audit.mem_Z_16
  · exact Audit.mem_Z_17
  · exact Audit.mem_Z_18
  · exact Audit.mem_Z_19
  · exact Audit.mem_Z_20
  · exact Audit.mem_Z_21
  · exact Audit.mem_Z_22
  · exact Audit.mem_Z_23
  · exact Audit.mem_Z_24
  · exact Audit.mem_Z_25
  · exact Audit.mem_Z_26
  · exact Audit.mem_Z_27
  · exact Audit.mem_Z_28
  · exact Audit.mem_Z_29
  · exact Audit.mem_Z_30
  · exact Audit.mem_Z_31
  · exact Audit.mem_Z_32
  · exact Audit.mem_Z_33
  · exact Audit.mem_Z_34
  · exact Audit.mem_Z_35
  · exact Audit.mem_Z_36
  · exact Audit.mem_Z_37
  · exact Audit.mem_Z_38
  · exact Audit.mem_Z_39
  · exact Audit.mem_Z_40
  · exact Audit.mem_ZHU_1
  · exact Audit.mem_ZHU_2
  · exact Audit.mem_ZHU_3
  · exact Audit.mem_ZHU_4
  · exact Audit.mem_ZHU_5
  · exact Audit.mem_ZHU_6
  · exact Audit.mem_ZHU_7
  · exact Audit.mem_ZHU_8
  · exact Audit.mem_ZHU_9
  · exact Audit.mem_ZHU_10
  · exact Audit.mem_ZHU_11
  · exact Audit.mem_ZHU_12
  · exact Audit.mem_SUN_1
  · exact Audit.mem_SUN_2
  · exact Audit.mem_SUN_3
  · exact Audit.mem_SUN_4
  · exact Audit.mem_SUN_5
  · exact Audit.mem_SUN_6
  · exact Audit.mem_SUN_7
  · exact Audit.mem_SUN_8
  · exact Audit.mem_SUN_9
  · exact Audit.mem_SUN_10
  · exact Audit.mem_SUN_11
  · exact Audit.mem_SUN_12
  · exact Audit.mem_SUN_13
  · exact Audit.mem_SUN_14
  · exact Audit.mem_CHU_1
  · exact Audit.mem_CHU_2
  · exact Audit.mem_CHU_3
  · exact Audit.mem_CHU_4
  · exact Audit.mem_CHU_5
  · exact Audit.mem_CHU_6
  · exact Audit.mem_CHU_7
  · exact Audit.mem_CHU_8
  · exact Audit.mem_CHU_9
  · exact Audit.mem_CHU_10
  · exact Audit.mem_LIJ_1
  · exact Audit.mem_LIJ_2
  · exact Audit.mem_LIJ_3
  · exact Audit.mem_LIJ_4
  · exact Audit.mem_LIJ_5
  · exact Audit.mem_LIJ_6
  · exact Audit.mem_LIJ_7
  · exact Audit.mem_LIJ_8
  · exact Audit.mem_LIJ_9
  · exact Audit.mem_LIJ_10
  · exact Audit.mem_LIJ_11
  · exact Audit.mem_LIJ_12
  · exact Audit.mem_LIJ_13
  · exact Audit.mem_LIJ_14
  · exact Audit.mem_ZA_1
  · exact Audit.mem_ZA_2
  · exact Audit.mem_ZA_3
  · exact Audit.mem_ZA_4
  · exact Audit.mem_ZA_5
  · exact Audit.mem_ZA_6
  · exact Audit.mem_ZA_7
  · exact Audit.mem_ZA_8
  · exact Audit.mem_ZA_9
  · exact Audit.mem_ZA_10
  · exact Audit.mem_ZA_11
  · exact Audit.mem_ZA_12
  · exact Audit.mem_ZA_13
  · exact Audit.mem_ZA_14
  · exact Audit.mem_ZA_15
  · exact Audit.mem_ZA_16
  · exact Audit.mem_ZA_17
  · exact Audit.mem_ZA_18
  · exact Audit.mem_ZA_19
  · exact Audit.mem_ZA_20

theorem operator_table_complete (id : OperatorId) : CoveredOperator id := by
  cases id
  · exact Audit.covered_R_1
  · exact Audit.covered_R_2
  · exact Audit.covered_R_3
  · exact Audit.covered_R_4
  · exact Audit.covered_R_5
  · exact Audit.covered_R_6
  · exact Audit.covered_R_7
  · exact Audit.covered_R_8
  · exact Audit.covered_R_9
  · exact Audit.covered_R_10
  · exact Audit.covered_R_11
  · exact Audit.covered_R_12
  · exact Audit.covered_R_13
  · exact Audit.covered_R_14
  · exact Audit.covered_R_15
  · exact Audit.covered_C_1
  · exact Audit.covered_C_2
  · exact Audit.covered_C_3
  · exact Audit.covered_C_4
  · exact Audit.covered_C_5
  · exact Audit.covered_C_6
  · exact Audit.covered_C_7
  · exact Audit.covered_C_8
  · exact Audit.covered_T_1
  · exact Audit.covered_T_2
  · exact Audit.covered_T_3
  · exact Audit.covered_T_4
  · exact Audit.covered_T_5
  · exact Audit.covered_T_6
  · exact Audit.covered_T_7
  · exact Audit.covered_T_8
  · exact Audit.covered_T_9
  · exact Audit.covered_T_10
  · exact Audit.covered_T_11
  · exact Audit.covered_T_12
  · exact Audit.covered_T_13
  · exact Audit.covered_T_14
  · exact Audit.covered_T_15
  · exact Audit.covered_F_1
  · exact Audit.covered_F_2
  · exact Audit.covered_F_3
  · exact Audit.covered_F_4
  · exact Audit.covered_F_5
  · exact Audit.covered_F_6
  · exact Audit.covered_F_7
  · exact Audit.covered_F_8
  · exact Audit.covered_F_9
  · exact Audit.covered_F_10
  · exact Audit.covered_F_11
  · exact Audit.covered_F_12
  · exact Audit.covered_B_1
  · exact Audit.covered_B_2
  · exact Audit.covered_B_3
  · exact Audit.covered_B_4
  · exact Audit.covered_B_5
  · exact Audit.covered_B_6
  · exact Audit.covered_B_7
  · exact Audit.covered_B_8
  · exact Audit.covered_Q_1
  · exact Audit.covered_Q_2
  · exact Audit.covered_Q_3
  · exact Audit.covered_Q_4
  · exact Audit.covered_Q_5
  · exact Audit.covered_Q_6
  · exact Audit.covered_Q_7
  · exact Audit.covered_Q_8
  · exact Audit.covered_K_1
  · exact Audit.covered_K_2
  · exact Audit.covered_K_3
  · exact Audit.covered_K_4
  · exact Audit.covered_K_5
  · exact Audit.covered_K_6
  · exact Audit.covered_K_7
  · exact Audit.covered_K_8
  · exact Audit.covered_M_1
  · exact Audit.covered_M_2
  · exact Audit.covered_M_3
  · exact Audit.covered_M_4
  · exact Audit.covered_M_5
  · exact Audit.covered_M_6
  · exact Audit.covered_M_7
  · exact Audit.covered_M_8
  · exact Audit.covered_N_1
  · exact Audit.covered_N_2
  · exact Audit.covered_N_3
  · exact Audit.covered_N_4
  · exact Audit.covered_N_5
  · exact Audit.covered_N_6
  · exact Audit.covered_N_7
  · exact Audit.covered_N_8
  · exact Audit.covered_I_1
  · exact Audit.covered_I_2
  · exact Audit.covered_I_3
  · exact Audit.covered_I_4
  · exact Audit.covered_I_5
  · exact Audit.covered_I_6
  · exact Audit.covered_I_7
  · exact Audit.covered_I_8
  · exact Audit.covered_I_9
  · exact Audit.covered_S_1
  · exact Audit.covered_S_2
  · exact Audit.covered_S_3
  · exact Audit.covered_S_4
  · exact Audit.covered_S_5
  · exact Audit.covered_S_6
  · exact Audit.covered_S_7
  · exact Audit.covered_S_8
  · exact Audit.covered_S_9
  · exact Audit.covered_S_10
  · exact Audit.covered_S_11
  · exact Audit.covered_S_12
  · exact Audit.covered_S_13
  · exact Audit.covered_S_14
  · exact Audit.covered_S_15
  · exact Audit.covered_S_16
  · exact Audit.covered_S_17
  · exact Audit.covered_S_18
  · exact Audit.covered_S_19
  · exact Audit.covered_S_20
  · exact Audit.covered_H_1
  · exact Audit.covered_H_2
  · exact Audit.covered_H_3
  · exact Audit.covered_H_4
  · exact Audit.covered_H_5
  · exact Audit.covered_H_6
  · exact Audit.covered_H_7
  · exact Audit.covered_H_8
  · exact Audit.covered_P_1
  · exact Audit.covered_P_2
  · exact Audit.covered_P_3
  · exact Audit.covered_P_4
  · exact Audit.covered_P_5
  · exact Audit.covered_P_6
  · exact Audit.covered_P_7
  · exact Audit.covered_P_8
  · exact Audit.covered_P_9
  · exact Audit.covered_P_10
  · exact Audit.covered_P_11
  · exact Audit.covered_P_12
  · exact Audit.covered_P_13
  · exact Audit.covered_P_14
  · exact Audit.covered_P_15
  · exact Audit.covered_P_16
  · exact Audit.covered_P_17
  · exact Audit.covered_P_18
  · exact Audit.covered_P_19
  · exact Audit.covered_P_20
  · exact Audit.covered_P_21
  · exact Audit.covered_P_22
  · exact Audit.covered_P_23
  · exact Audit.covered_P_24
  · exact Audit.covered_G_1
  · exact Audit.covered_G_2
  · exact Audit.covered_G_3
  · exact Audit.covered_G_4
  · exact Audit.covered_G_5
  · exact Audit.covered_G_6
  · exact Audit.covered_G_7
  · exact Audit.covered_G_8
  · exact Audit.covered_G_9
  · exact Audit.covered_G_10
  · exact Audit.covered_G_11
  · exact Audit.covered_A_1
  · exact Audit.covered_A_2
  · exact Audit.covered_A_3
  · exact Audit.covered_A_4
  · exact Audit.covered_A_5
  · exact Audit.covered_A_6
  · exact Audit.covered_A_7
  · exact Audit.covered_A_8
  · exact Audit.covered_A_9
  · exact Audit.covered_A_10
  · exact Audit.covered_A_11
  · exact Audit.covered_A_12
  · exact Audit.covered_A_13
  · exact Audit.covered_A_14
  · exact Audit.covered_A_15
  · exact Audit.covered_A_16
  · exact Audit.covered_A_17
  · exact Audit.covered_A_18
  · exact Audit.covered_A_19
  · exact Audit.covered_A_20
  · exact Audit.covered_D_1
  · exact Audit.covered_D_2
  · exact Audit.covered_D_3
  · exact Audit.covered_D_4
  · exact Audit.covered_D_5
  · exact Audit.covered_D_6
  · exact Audit.covered_D_7
  · exact Audit.covered_D_8
  · exact Audit.covered_D_9
  · exact Audit.covered_D_10
  · exact Audit.covered_E_1
  · exact Audit.covered_E_2
  · exact Audit.covered_E_3
  · exact Audit.covered_E_4
  · exact Audit.covered_E_5
  · exact Audit.covered_E_6
  · exact Audit.covered_E_7
  · exact Audit.covered_E_8
  · exact Audit.covered_E_9
  · exact Audit.covered_L_1
  · exact Audit.covered_L_2
  · exact Audit.covered_L_3
  · exact Audit.covered_L_4
  · exact Audit.covered_L_5
  · exact Audit.covered_L_6
  · exact Audit.covered_L_7
  · exact Audit.covered_L_8
  · exact Audit.covered_L_9
  · exact Audit.covered_L_10
  · exact Audit.covered_L_11
  · exact Audit.covered_L_12
  · exact Audit.covered_L_13
  · exact Audit.covered_L_14
  · exact Audit.covered_L_15
  · exact Audit.covered_L_16
  · exact Audit.covered_Y_1
  · exact Audit.covered_Y_2
  · exact Audit.covered_Y_3
  · exact Audit.covered_Y_4
  · exact Audit.covered_Y_5
  · exact Audit.covered_Y_6
  · exact Audit.covered_Y_7
  · exact Audit.covered_Y_8
  · exact Audit.covered_Y_9
  · exact Audit.covered_Y_10
  · exact Audit.covered_Y_11
  · exact Audit.covered_Y_12
  · exact Audit.covered_Y_13
  · exact Audit.covered_Y_14
  · exact Audit.covered_Y_15
  · exact Audit.covered_Y_16
  · exact Audit.covered_Y_17
  · exact Audit.covered_Y_18
  · exact Audit.covered_Y_19
  · exact Audit.covered_Y_20
  · exact Audit.covered_Y_21
  · exact Audit.covered_Y_22
  · exact Audit.covered_Y_23
  · exact Audit.covered_Y_24
  · exact Audit.covered_Y_25
  · exact Audit.covered_Y_26
  · exact Audit.covered_Y_27
  · exact Audit.covered_Y_28
  · exact Audit.covered_X_1
  · exact Audit.covered_X_2
  · exact Audit.covered_X_3
  · exact Audit.covered_X_4
  · exact Audit.covered_X_5
  · exact Audit.covered_X_6
  · exact Audit.covered_X_7
  · exact Audit.covered_X_8
  · exact Audit.covered_X_9
  · exact Audit.covered_X_10
  · exact Audit.covered_X_11
  · exact Audit.covered_X_12
  · exact Audit.covered_X_13
  · exact Audit.covered_X_14
  · exact Audit.covered_X_15
  · exact Audit.covered_X_16
  · exact Audit.covered_Z_1
  · exact Audit.covered_Z_2
  · exact Audit.covered_Z_3
  · exact Audit.covered_Z_4
  · exact Audit.covered_Z_5
  · exact Audit.covered_Z_6
  · exact Audit.covered_Z_7
  · exact Audit.covered_Z_8
  · exact Audit.covered_Z_9
  · exact Audit.covered_Z_10
  · exact Audit.covered_Z_11
  · exact Audit.covered_Z_12
  · exact Audit.covered_Z_13
  · exact Audit.covered_Z_14
  · exact Audit.covered_Z_15
  · exact Audit.covered_Z_16
  · exact Audit.covered_Z_17
  · exact Audit.covered_Z_18
  · exact Audit.covered_Z_19
  · exact Audit.covered_Z_20
  · exact Audit.covered_Z_21
  · exact Audit.covered_Z_22
  · exact Audit.covered_Z_23
  · exact Audit.covered_Z_24
  · exact Audit.covered_Z_25
  · exact Audit.covered_Z_26
  · exact Audit.covered_Z_27
  · exact Audit.covered_Z_28
  · exact Audit.covered_Z_29
  · exact Audit.covered_Z_30
  · exact Audit.covered_Z_31
  · exact Audit.covered_Z_32
  · exact Audit.covered_Z_33
  · exact Audit.covered_Z_34
  · exact Audit.covered_Z_35
  · exact Audit.covered_Z_36
  · exact Audit.covered_Z_37
  · exact Audit.covered_Z_38
  · exact Audit.covered_Z_39
  · exact Audit.covered_Z_40
  · exact Audit.covered_ZHU_1
  · exact Audit.covered_ZHU_2
  · exact Audit.covered_ZHU_3
  · exact Audit.covered_ZHU_4
  · exact Audit.covered_ZHU_5
  · exact Audit.covered_ZHU_6
  · exact Audit.covered_ZHU_7
  · exact Audit.covered_ZHU_8
  · exact Audit.covered_ZHU_9
  · exact Audit.covered_ZHU_10
  · exact Audit.covered_ZHU_11
  · exact Audit.covered_ZHU_12
  · exact Audit.covered_SUN_1
  · exact Audit.covered_SUN_2
  · exact Audit.covered_SUN_3
  · exact Audit.covered_SUN_4
  · exact Audit.covered_SUN_5
  · exact Audit.covered_SUN_6
  · exact Audit.covered_SUN_7
  · exact Audit.covered_SUN_8
  · exact Audit.covered_SUN_9
  · exact Audit.covered_SUN_10
  · exact Audit.covered_SUN_11
  · exact Audit.covered_SUN_12
  · exact Audit.covered_SUN_13
  · exact Audit.covered_SUN_14
  · exact Audit.covered_CHU_1
  · exact Audit.covered_CHU_2
  · exact Audit.covered_CHU_3
  · exact Audit.covered_CHU_4
  · exact Audit.covered_CHU_5
  · exact Audit.covered_CHU_6
  · exact Audit.covered_CHU_7
  · exact Audit.covered_CHU_8
  · exact Audit.covered_CHU_9
  · exact Audit.covered_CHU_10
  · exact Audit.covered_LIJ_1
  · exact Audit.covered_LIJ_2
  · exact Audit.covered_LIJ_3
  · exact Audit.covered_LIJ_4
  · exact Audit.covered_LIJ_5
  · exact Audit.covered_LIJ_6
  · exact Audit.covered_LIJ_7
  · exact Audit.covered_LIJ_8
  · exact Audit.covered_LIJ_9
  · exact Audit.covered_LIJ_10
  · exact Audit.covered_LIJ_11
  · exact Audit.covered_LIJ_12
  · exact Audit.covered_LIJ_13
  · exact Audit.covered_LIJ_14
  · exact Audit.covered_ZA_1
  · exact Audit.covered_ZA_2
  · exact Audit.covered_ZA_3
  · exact Audit.covered_ZA_4
  · exact Audit.covered_ZA_5
  · exact Audit.covered_ZA_6
  · exact Audit.covered_ZA_7
  · exact Audit.covered_ZA_8
  · exact Audit.covered_ZA_9
  · exact Audit.covered_ZA_10
  · exact Audit.covered_ZA_11
  · exact Audit.covered_ZA_12
  · exact Audit.covered_ZA_13
  · exact Audit.covered_ZA_14
  · exact Audit.covered_ZA_15
  · exact Audit.covered_ZA_16
  · exact Audit.covered_ZA_17
  · exact Audit.covered_ZA_18
  · exact Audit.covered_ZA_19
  · exact Audit.covered_ZA_20

end SSBX.Text.WenyanOperators
