/-
# Wen.Layered.Finite -- finite cardinality and generator closure helpers

This file stays at the generic `BitSpace n` specification layer.  It does not
specialize to V4 or any bridge layer.
-/

import SSBX.Foundation.Wen.Layered.BitSpace
import SSBX.Foundation.Wen.Layered.Information
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.List.Basic

namespace SSBX.Foundation.Wen.Layered

namespace BitSpace

instance (priority := 100) instFintype (n : Nat) : Fintype (BitSpace n) :=
  inferInstance

instance (priority := 100) instDecidableEq (n : Nat) : DecidableEq (BitSpace n) :=
  inferInstance

/-- The generic `n`-slot bit space has exactly `2^n` points. -/
theorem card_eq_two_pow (n : Nat) :
    Fintype.card (BitSpace n) = 2 ^ n := by
  simp [BitSpace, Slot]

/-- XOR-fold a finite list of bit-space elements. -/
def foldXor {n : Nat} : List (BitSpace n) → BitSpace n
  | [] => zero
  | g :: gs => xor g (foldXor gs)

@[simp] theorem foldXor_nil {n : Nat} :
    foldXor ([] : List (BitSpace n)) = zero :=
  rfl

@[simp] theorem foldXor_cons {n : Nat} (g : BitSpace n) (gs : List (BitSpace n)) :
    foldXor (g :: gs) = xor g (foldXor gs) :=
  rfl

theorem foldXor_append {n : Nat} (xs ys : List (BitSpace n)) :
    foldXor (xs ++ ys) = xor (foldXor xs) (foldXor ys) := by
  induction xs with
  | nil =>
      simp
  | cons x xs ih =>
      simp [ih, xor_assoc]

/-- Elements generated by XOR-folding a finite list drawn from `gens`. -/
def spanListCarrier {n : Nat} (gens : List (BitSpace n)) (g : BitSpace n) : Prop :=
  ∃ chosen : List (BitSpace n),
    (∀ x : BitSpace n, x ∈ chosen → x ∈ gens) ∧ foldXor chosen = g

theorem foldXor_mem_of_forall_mem {n : Nat} {H : Subgroup n}
    {chosen : List (BitSpace n)}
    (hchosen : ∀ x : BitSpace n, x ∈ chosen → H.carrier x) :
    H.carrier (foldXor chosen) := by
  induction chosen with
  | nil =>
      exact H.zero_mem
  | cons x xs ih =>
      exact H.xor_mem
        (hchosen x (by simp))
        (ih (by
          intro y hy
          exact hchosen y (by simp [hy])))

/-- The subgroup generated by a finite list of bit-space elements. -/
def spanList {n : Nat} (gens : List (BitSpace n)) : Subgroup n where
  carrier := spanListCarrier gens
  zero_mem := by
    refine ⟨[], ?_, rfl⟩
    intro x hx
    simp at hx
  xor_mem := by
    intro a b ha hb
    rcases ha with ⟨as, has, has_fold⟩
    rcases hb with ⟨bs, hbs, hbs_fold⟩
    refine ⟨as ++ bs, ?_, ?_⟩
    · intro x hx
      rcases List.mem_append.mp hx with hx | hx
      · exact has x hx
      · exact hbs x hx
    · rw [foldXor_append, has_fold, hbs_fold]

theorem mem_spanList_of_mem_generators {n : Nat} {gens : List (BitSpace n)}
    {g : BitSpace n} (hg : g ∈ gens) :
    (spanList gens).carrier g := by
  refine ⟨[g], ?_, ?_⟩
  · intro x hx
    have hxg : x = g := by
      simpa using hx
    simpa [hxg] using hg
  · simp [foldXor]

theorem spanList_le {n : Nat} {gens : List (BitSpace n)} {H : Subgroup n}
    (hgens : ∀ g : BitSpace n, g ∈ gens → H.carrier g) :
    ∀ g : BitSpace n, (spanList gens).carrier g → H.carrier g := by
  intro g hg
  rcases hg with ⟨chosen, hchosen, hfold⟩
  rw [← hfold]
  exact foldXor_mem_of_forall_mem (H := H) (by
    intro x hx
    exact hgens x (hchosen x hx))

theorem finite_summary (n : Nat) (gens : List (BitSpace n)) :
    Fintype.card (BitSpace n) = 2 ^ n
    ∧ (spanList gens).carrier zero
    ∧ (∀ a b : BitSpace n,
        (spanList gens).carrier a →
        (spanList gens).carrier b →
        (spanList gens).carrier (xor a b))
    ∧ (∀ g : BitSpace n, g ∈ gens → (spanList gens).carrier g)
    ∧ (∀ H : Subgroup n,
        (∀ g : BitSpace n, g ∈ gens → H.carrier g) →
        ∀ g : BitSpace n, (spanList gens).carrier g → H.carrier g) :=
  ⟨card_eq_two_pow n,
    (spanList gens).zero_mem,
    fun _ _ ha hb => (spanList gens).xor_mem ha hb,
    fun _ hg => mem_spanList_of_mem_generators hg,
    fun H hgens g hg => spanList_le (H := H) hgens g hg⟩

end BitSpace

end SSBX.Foundation.Wen.Layered
