/-
# Foundation.R.UniquenessAlgebraic — T5 algebraic-class: P1+P2+P7b(k) ⟹ R-family-over-k

Per `docs-next/10_formal_形式/gut-roadmap.md` **Phase 2 (T5-A algebraic
generalisation)** and the user directive "推广到general" (generalise
beyond Bool):

> **GUT-B algebraic form**: any structure satisfying the *core* P-closure
> clauses over a field-valued δ-realisation `k`, plus the ring-iso
> closure at carrier 4, is layerwise type-equivalent to R-family-over-k
> AND ring-iso to `Matrix (Fin 2) (Fin 2) k` at carrier 4.

This file lifts `T5_general` (the polymorphic *layerwise* statement in
`UniquenessGeneral.lean`) to the **algebraic-class** statement: when δ
is a field `k` (so `Matrix (Fin 2) (Fin 2) k` is a ring), we get not
only the layerwise type-equivalence but also a **ring iso** at carrier
4 with the standard 2×2 matrix ring over `k`.

## What this delivers

* `P1P7_Satisfier_Algebraic (k : Type) [Field k] [Fintype k] [DecidableEq k]`
  — extends `P1P7_Core k` with a ring-iso closure at carrier 4:
  `carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k`, together with the `Mul`
  and `Add` instances needed to state it.
* `T5_algebraic` — the combined statement: layerwise type-equiv
  (`carrier N ≃ R N k` at every N) **and** ring-iso refinement
  at N = 4 (`carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k`).
* `forgetF2ToAlgebraic_ZMod2` — F₂-Boolean corollary: every
  `P1P7_Satisfier_F2` lifts to a `P1P7_Satisfier_Algebraic (ZMod 2)`
  via the `Bool ≃+* ZMod 2` and `Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`
  bridges from `PhaseZero/TP7bUniqueness.lean`.
* `T5_A_ringEquiv_at_4_zmod2` — the existing
  `UniquenessF2.T5_A_ringEquiv_at_4` (which lands in `R 4 ≃+* Mat2F2`)
  becomes a corollary at `k = ZMod 2` (via the entrywise lift).
* `T5_algebraic_at_ZMod2` — char(k) = 2 demo instance: concrete
  closure at `k = ZMod 2`, with `R N (ZMod 2) ≃ R N Bool` at the
  layerwise level (via `Bool ≃ ZMod 2`).

## Scope guidance

This file does **not** attempt to prove that Strategy A (the
`BooleanRing → R N` embedding from `StrategyA.lean`) lifts to general
k.  That requires Wedderburn-Artin for `k`-algebras and is out of
scope.  Instead, the `p7b_ring_equiv` field is **assumed** as part of
the satisfier's data (same pattern as `P1P7_Satisfier_F2` does for the
F₂ case).  The theorem packages what follows *given* the closure data.

## Doctrinal anchor

* `docs-next/10_formal_形式/gut-roadmap.md` Phase 2 (T5-A) §十一
  (polymorphic generalisation; F₂ → general δ).
* `Foundation/R/UniquenessGeneral.lean` — `P1P7_Core δ` + `T5_general`
  (δ-polymorphic layerwise).
* `Foundation/R/UniquenessF2.lean` — `P1P7_Satisfier_F2` + `T5_A` +
  `T5_A_ringEquiv_at_4` (F₂-Boolean specialization).
* `Foundation/R/PhaseZero.lean` — `T_P7b_ring_equiv : R 4 ≃+* Mat2F2`.
* `Foundation/R/PhaseZero/TP7bUniqueness.lean` —
  `boolRingEquivZMod2 : Bool ≃+* ZMod 2` and
  `T_P7b_mat2f2_equiv_matrix_zmod2 : Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`.

## Constraints honoured

* No new axioms.
* No `sorry`.
* Targeted build: `lake build SSBX.Foundation.R.UniquenessAlgebraic`.
-/

import SSBX.Foundation.R.UniquenessGeneral
import SSBX.Foundation.R.UniquenessF2
import SSBX.Foundation.R.PhaseZero
import SSBX.Foundation.R.PhaseZero.TP7bUniqueness
import Mathlib.Data.Matrix.Mul
import Mathlib.Algebra.Field.ZMod
import Mathlib.Data.ZMod.Basic

namespace SSBX.Foundation.R.UniquenessAlgebraic

open SSBX.Foundation.R
open SSBX.Foundation.R.UniquenessGeneral
open SSBX.Foundation.R.UniquenessF2
open SSBX.Foundation.R.PhaseZero

/-! ## § 0 Stable instance aliases for `Matrix (Fin 2) (Fin 2) k`

`Mul` and `Add` on `Matrix m m α` are auto-generated by Mathlib with
long instance names (`Matrix.instMulOfFintypeOfAddCommMonoid` and
`Matrix.add`).  For ergonomic use in `@RingEquiv` arguments — where the
instance terms must be referenceable — we provide stable aliases below.

These are *not* new instances (we use `def` not `instance`); they are
named witnesses that can be substituted into `@RingEquiv` slots. -/

/-- Stable alias for the `Mul` instance on `Matrix (Fin 2) (Fin 2) k`,
    for any field k (or more generally, any ring k).  Equal to the
    Mathlib-auto-generated `Matrix.instMulOfFintypeOfAddCommMonoid`. -/
@[reducible] def matMulInstance (k : Type) [Field k] :
    Mul (Matrix (Fin 2) (Fin 2) k) :=
  inferInstance

/-- Stable alias for the `Add` instance on `Matrix (Fin 2) (Fin 2) k`,
    for any field k.  Equal to the Mathlib-auto-generated `Matrix.add`. -/
@[reducible] def matAddInstance (k : Type) [Field k] :
    Add (Matrix (Fin 2) (Fin 2) k) :=
  inferInstance

/-! ## § 1 The `P1P7_Satisfier_Algebraic k` structure

**Design**: extend `P1P7_Core k` with the *minimum* additional data
needed to state the ring-iso refinement at carrier 4.  Concretely:

* `p7b_mul_instance : Mul (carrier 4)` — the multiplicative structure
  on carrier 4 (the operation-algebra layer).
* `p7b_add_instance : Add (carrier 4)` — the additive structure on
  carrier 4.
* `p7b_ring_equiv : Nonempty (carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k)`
  — the ring-iso closure asserting that carrier 4 is, as a k-algebra,
  the standard 2×2 matrix ring over k.

For `k = ZMod 2` (the char-2 demo case), this recovers the F₂-Boolean
content of `P1P7_Satisfier_F2`'s `p7b_mat2F2_equiv` modulo the Mathlib
bridge `Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`.

For general fields k (char(k) = p arbitrary), the same shape applies:
the satisfier *asserts* the closure as data, and `T5_algebraic` packages
the layerwise + ring-iso content as a single theorem.

**Optional content** — bilinear forms `p3_dot : ∀ N, carrier N → carrier N → k`
(k-valued, generalizing the Bool-valued F₂ version).  We provide
*existence* of `p3_dot` and symmetry as the minimum bilinear data; the
char-2-specific `sigma`/`arf` content is *not* required at this level
(it lives in the F₂ specialization).
-/

/-- **P1P7_Satisfier_Algebraic k** — the algebraic-class extension of
    `P1P7_Core k`.

    For any field `k` with `[Fintype]` and `[DecidableEq]`, a satisfier
    of P1+P2 (via the embedded `P1P7_Core k`) plus the **ring-iso
    closure at carrier 4** (`carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k`)
    plus an **optional k-valued symmetric bilinear form** at every layer.

    The conclusion of `T5_algebraic` is the combined statement:

    * layerwise type-equivalence `carrier N ≃ R N k` (from `T5_general`);
    * ring-iso refinement `carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k` (from
      the structure's own `p7b_ring_equiv` field). -/
structure P1P7_Satisfier_Algebraic (k : Type) [Field k] [Fintype k]
    [DecidableEq k] extends P1P7_Core k where
  /-- **P7b Mul on `carrier 4`** — the multiplicative structure on the
      operation-algebra layer.  Needed to state the `RingEquiv` field
      below (the target `Matrix (Fin 2) (Fin 2) k` has `Mul` from
      `Matrix.nonUnitalNonAssocSemiring` over the field k). -/
  p7b_mul_instance : Mul (toP1P7_Core.carrier 4)
  /-- **P7b Add on `carrier 4`** — the additive structure on the
      operation-algebra layer.  Needed to state the `RingEquiv` field
      below. -/
  p7b_add_instance : Add (toP1P7_Core.carrier 4)
  /-- **P7b ring-iso closure** — `carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k`
      as k-algebras.

      For `k = ZMod 2`, this is the polymorphic generalization of the
      F₂-Boolean `T_P7b_ring_equiv : R 4 ≃+* Mat2F2` modulo the
      `Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)` Mathlib bridge.

      For general fields k, the same shape applies — the satisfier
      asserts this closure as data, and `T5_algebraic` packages the
      layerwise + ring-iso content. -/
  p7b_ring_equiv :
      @Nonempty
        (@RingEquiv (toP1P7_Core.carrier 4) (Matrix (Fin 2) (Fin 2) k)
          p7b_mul_instance (matMulInstance k)
          p7b_add_instance (matAddInstance k))
  /-- **P3 (optional) k-valued symmetric bilinear form** at every layer.
      Generalizes the Bool-valued `p3_dot` of `P1P7_Satisfier_F2` to a
      k-valued form for general fields k.

      Symmetry is enforced by `p3_dot_symm`.  Other content (alternation,
      decomposition `dot = sigma ⊕ LL`, Arf invariant) is char-2
      specific and lives in the F₂ specialisation, not at this
      algebraic-class level. -/
  p3_dot : ∀ N, toP1P7_Core.carrier N → toP1P7_Core.carrier N → k
  /-- **P3 symmetry** — `dot` is symmetric at every layer. -/
  p3_dot_symm : ∀ N (u v : toP1P7_Core.carrier N), p3_dot N u v = p3_dot N v u

/-! ## § 2 The main theorem: `T5_algebraic`

The combined statement: layerwise type-equivalence (from `T5_general`)
plus ring-iso refinement at carrier 4 (from the structure's own
`p7b_ring_equiv` field).

This is the **algebraic-class form** of T5-A — the polymorphic GUT-B
claim including ring/bilinear structure for any field-valued
realization k.
-/

/-- **T5-algebraic (GUT-B algebraic form)** — algebraic-class
    uniqueness.

    For any field `k` with `[Fintype]` and `[DecidableEq]`, any
    `S : P1P7_Satisfier_Algebraic k`:

    1. has layerwise type-equivalence `carrier N ≃ R N k` at every
       layer (the GUT-B layerwise content, inherited from
       `T5_general`);
    2. has a ring-iso at the operation-algebra layer:
       `carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k`.

    Per `docs-next/10_formal_形式/gut-roadmap.md` Phase 2 (T5-A
    algebraic generalisation) and the user directive "推广到general". -/
theorem T5_algebraic {k : Type} [Field k] [Fintype k] [DecidableEq k]
    (S : P1P7_Satisfier_Algebraic k) :
    (∀ N, Nonempty (S.toP1P7_Core.carrier N ≃ R N k))
  ∧ (@Nonempty
        (@RingEquiv (S.toP1P7_Core.carrier 4) (Matrix (Fin 2) (Fin 2) k)
          S.p7b_mul_instance (matMulInstance k)
          S.p7b_add_instance (matAddInstance k))) := by
  refine ⟨?_, S.p7b_ring_equiv⟩
  intro N
  -- ZMod 2 etc. are inhabited via Field's `Zero`; for general Field k,
  -- `Inhabited k` is also available since `Field` includes `Zero`.
  haveI : Inhabited k := ⟨0⟩
  exact T5_general S.toP1P7_Core N

/-! ## § 3 F₂-Boolean corollary via ZMod 2

The existing F₂-Boolean `P1P7_Satisfier_F2` (where `carrier 4 ≃+* Mat2F2`,
i.e. ≃+* over `Bool`-valued matrices) lifts to a `P1P7_Satisfier_Algebraic
(ZMod 2)` (where `carrier 4 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`, i.e.
the standard Mathlib matrix ring over the prime field `ZMod 2`).

The lift uses two bridges from `PhaseZero/TP7bUniqueness.lean`:

* `Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)` — entrywise lift of
  `Bool ≃+* ZMod 2`.
* `Bool ≃+* ZMod 2` — for the cardinality bridge `|carrier 1| = 2 =
  |ZMod 2|` (so that `P1P7_Core (ZMod 2)` is obtainable).

Note `Fintype.card (ZMod 2) = 2` (Mathlib's `ZMod.card`).
-/

/-- `Fintype.card (ZMod 2) = 2`. -/
private theorem zmod2_card : Fintype.card (ZMod 2) = 2 := by
  decide

/-- **Forgetful map `P1P7_Satisfier_F2 → P1P7_Core (ZMod 2)`** — the
    F₂-Boolean satisfier provides the polymorphic core data over the
    prime field `ZMod 2`.

    The carrier family is unchanged; only the base-cardinality clause is
    rewritten from `|carrier 1| = 2` to `|carrier 1| = Fintype.card (ZMod 2)`. -/
def forgetF2ToCore_ZMod2 (S : P1P7_Satisfier_F2) : P1P7_Core (ZMod 2) where
  carrier := S.carrier
  fintype := S.fintype
  decEq := S.decEq
  p1_base_card := S.p1_base_card.trans zmod2_card.symm
  p2_directSum := S.p2_directSum

/-- **F₂-Boolean → algebraic at `k = ZMod 2`**.

    Every `P1P7_Satisfier_F2` lifts to a `P1P7_Satisfier_Algebraic (ZMod 2)`.

    Construction:
    * Core data: via `forgetF2ToCore_ZMod2`.
    * `p7b_mul_instance` / `p7b_add_instance`: inherited from the F₂
      satisfier's structure fields.
    * `p7b_ring_equiv`: composing `p7b_mat2F2_equiv` with the Mathlib
      bridge `Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`.
    * `p3_dot` (k-valued): obtained from the F₂ `p3_dot` (Bool-valued)
      by composing with `boolRingEquivZMod2`. -/
def forgetF2ToAlgebraic_ZMod2 (S : P1P7_Satisfier_F2) :
    P1P7_Satisfier_Algebraic (ZMod 2) where
  toP1P7_Core := forgetF2ToCore_ZMod2 S
  p7b_mul_instance := S.p7b_mul_instance
  p7b_add_instance := S.p7b_add_instance
  p7b_ring_equiv := by
    -- p7b_mat2F2_equiv : carrier 4 ≃+* Mat2F2
    -- Mathlib bridge   : Mat2F2 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)
    -- Compose.
    obtain ⟨eS⟩ := S.p7b_mat2F2_equiv
    letI : Mul (S.carrier 4) := S.p7b_mul_instance
    letI : Add (S.carrier 4) := S.p7b_add_instance
    exact ⟨eS.trans T_P7b_mat2f2_equiv_matrix_zmod2⟩
  p3_dot N u v := Mat2F2.boolToZMod2 (S.p3_dot N u v)
  p3_dot_symm := by
    intro N u v
    obtain ⟨hSymm, _, _, _, _⟩ := S.p3_identities
    rw [hSymm N u v]

/-- **T5-A ring iso at carrier 4, ZMod 2 form** — the existing
    `UniquenessF2.T5_A_ringEquiv_at_4` (which lands in
    `carrier 4 ≃+* R 4`, i.e. via `Mat2F2`) becomes a corollary at
    `k = ZMod 2`: `carrier 4 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`.

    Construction: apply `T5_algebraic` at the lifted satisfier
    `forgetF2ToAlgebraic_ZMod2 S`. -/
theorem T5_A_ringEquiv_at_4_zmod2 (S : P1P7_Satisfier_F2) :
    @Nonempty
      (@RingEquiv (S.carrier 4) (Matrix (Fin 2) (Fin 2) (ZMod 2))
        S.p7b_mul_instance (matMulInstance (ZMod 2))
        S.p7b_add_instance (matAddInstance (ZMod 2))) :=
  (T5_algebraic (forgetF2ToAlgebraic_ZMod2 S)).2

/-! ## § 4 char(k) = 2 demo at `k = ZMod 2`

A concrete instantiation showing the algebraic-class theorem applies
at the prime field `ZMod 2`.  We exhibit the **canonical R-family-over-ZMod 2**
as a `P1P7_Satisfier_Algebraic (ZMod 2)` and verify the conclusion of
`T5_algebraic`.

The carrier family is `R N (ZMod 2) = Fin N → ZMod 2`.  At carrier 4
this becomes `Fin 4 → ZMod 2`, and the ring iso target is
`Matrix (Fin 2) (Fin 2) (ZMod 2) = Fin 2 → Fin 2 → ZMod 2`.  The bijection
is currying.

For this demo we use the F₂-Boolean canonical R-family (= the Bool
substrate that `T5_A` applies to) lifted via `forgetF2ToAlgebraic_ZMod2`.
This gives a non-vacuous witness that the algebraic-class theorem has at
least one concrete model at `k = ZMod 2`.

Cardinality bridge: `|R N (ZMod 2)| = 2^N = |R N Bool|`, so the two
canonical R-families are non-canonically bijective at every layer.
-/

/-- **R-family-over-ZMod 2 cardinality** — `|R N (ZMod 2)| = 2^N`.
    Specialization of `R.card_eq_general` at `δ = ZMod 2`. -/
theorem R_zmod2_card_eq (N : ℕ) : Fintype.card (R N (ZMod 2)) = 2 ^ N := by
  rw [R.card_eq_general N (ZMod 2), zmod2_card]

/-- **R-family layerwise bridge** — `R N (ZMod 2) ≃ R N Bool` for every N.

    Both carriers are finite types with cardinality `2^N`
    (`R_zmod2_card_eq` and `R.card_eq` respectively); apply
    `Fintype.truncEquivOfCardEq`. -/
theorem R_zmod2_equiv_bool (N : ℕ) :
    Nonempty (R N (ZMod 2) ≃ R N Bool) := by
  have h1 : Fintype.card (R N (ZMod 2)) = 2 ^ N := R_zmod2_card_eq N
  have h2 : Fintype.card (R N Bool) = 2 ^ N := R.card_eq N
  have hcards : Fintype.card (R N (ZMod 2)) = Fintype.card (R N Bool) :=
    h1.trans h2.symm
  exact (Fintype.truncEquivOfCardEq
          (α := R N (ZMod 2)) (β := R N Bool) hcards).nonempty

/-- **Algebraic-class demo at ZMod 2** — `T5_algebraic` applied to
    the lift of any `P1P7_Satisfier_F2` gives the combined statement:

    1. layerwise type-equivalence `carrier N ≃ R N (ZMod 2)`;
    2. ring iso `carrier 4 ≃+* Matrix (Fin 2) (Fin 2) (ZMod 2)`. -/
theorem T5_algebraic_at_ZMod2 (S : P1P7_Satisfier_F2) :
    (∀ N, Nonempty (S.carrier N ≃ R N (ZMod 2)))
  ∧ (@Nonempty
        (@RingEquiv (S.carrier 4) (Matrix (Fin 2) (Fin 2) (ZMod 2))
          S.p7b_mul_instance (matMulInstance (ZMod 2))
          S.p7b_add_instance (matAddInstance (ZMod 2)))) :=
  T5_algebraic (forgetF2ToAlgebraic_ZMod2 S)

/-! ## § 5 Aggregator — full algebraic-class T5 content

The combined statement of GUT-B algebraic form, packaged as a single
theorem.  For any field k with the canonical instances and any
`P1P7_Satisfier_Algebraic k`:

* layerwise type-equivalence at every layer (carrier N ≃ R N k);
* k-valued symmetric bilinear form at every layer;
* ring-iso refinement at carrier 4 (carrier 4 ≃+* Matrix (Fin 2) (Fin 2) k);
* carrier cardinality matches `(|k|)^N`.

This is the algebraic-class version of `GUT_B_layerwise` from
`UniquenessGeneral.lean` — the same layerwise content plus the
ring-iso refinement at the carrier 4 operation-algebra layer.
-/

/-- **GUT-B algebraic aggregator** — the algebraic-class content of
    this file packaged as a single theorem.

    For any field `k` with the canonical Fintype + DecidableEq instances
    and any `P1P7_Satisfier_Algebraic k`:

    1. layerwise type-equivalence (from `T5_general`);
    2. carrier cardinality identity `|carrier N| = (|k|)^N`;
    3. ring-iso at carrier 4 (from `p7b_ring_equiv`);
    4. k-valued symmetric bilinear form at every layer (from `p3_dot`).

    Per `docs-next/10_formal_形式/gut-roadmap.md` v0.2 §十一 + the
    algebraic-class extension of Phase 2 T5-A. -/
theorem GUT_B_algebraic {k : Type} [Field k] [Fintype k] [DecidableEq k]
    (S : P1P7_Satisfier_Algebraic k) :
    -- 1. layerwise type-equivalence
    (∀ N, Nonempty (S.toP1P7_Core.carrier N ≃ R N k))
    -- 2. carrier cardinality identity (under the Fintype instance from the core)
  ∧ (∀ N,
      letI : Fintype (S.toP1P7_Core.carrier N) := S.toP1P7_Core.fintype N
      Fintype.card (S.toP1P7_Core.carrier N) = (Fintype.card k) ^ N)
    -- 3. ring-iso at carrier 4
  ∧ (@Nonempty
        (@RingEquiv (S.toP1P7_Core.carrier 4) (Matrix (Fin 2) (Fin 2) k)
          S.p7b_mul_instance (matMulInstance k)
          S.p7b_add_instance (matAddInstance k)))
    -- 4. k-valued symmetric bilinear form at every layer
  ∧ (∀ N (u v : S.toP1P7_Core.carrier N), S.p3_dot N u v = S.p3_dot N v u) := by
  haveI : Inhabited k := ⟨0⟩
  refine ⟨?_, ?_, S.p7b_ring_equiv, S.p3_dot_symm⟩
  · intro N; exact T5_general S.toP1P7_Core N
  · intro N; exact S.toP1P7_Core.carrier_card_eq N

end SSBX.Foundation.R.UniquenessAlgebraic
