#!/usr/bin/env python3
"""Generate and check docs-next derived indexes.

The authored documents under docs-next/ explain the project.  This script owns
only factual indexes under docs-next/_generated so build state, module maps,
claim ledgers, diagrams, and cross references have one repeatable source.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

GENERATOR_VERSION = "docs-next-v1"
DEFAULT_OUT = Path("docs-next/_generated")
EXCLUDED_DIRS = {".git", ".lake", ".claude"}
DOCS_GENERATED_PART = ("docs-next", "_generated")

DECL_RE = re.compile(
    r"^\s*(?:noncomputable\s+)?(?:partial\s+)?"
    r"(inductive|structure|class|def|abbrev|theorem|lemma|axiom|opaque)\s+([^(:=\s]+)",
    re.MULTILINE,
)


@dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: str


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def stable_json(data: object) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def should_skip(path: Path, root: Path, include_archive: bool) -> bool:
    parts = path.relative_to(root).parts
    if any(part in EXCLUDED_DIRS for part in parts):
        return True
    if DOCS_GENERATED_PART[0] in parts:
        idx = parts.index(DOCS_GENERATED_PART[0])
        if parts[idx : idx + 2] == DOCS_GENERATED_PART:
            return True
    if not include_archive and parts and parts[0] == "史料":
        return True
    return False


def git_tracked_files(root: Path) -> set[str] | None:
    try:
        proc = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    entries = proc.stdout.decode("utf-8").split("\0")
    return {entry for entry in entries if entry}


def files(root: Path, suffixes: tuple[str, ...], include_archive: bool = False) -> list[Path]:
    out: list[Path] = []
    tracked = git_tracked_files(root)
    for current, dirs, filenames in os.walk(root):
        current_path = Path(current)
        dirs[:] = [
            d for d in dirs
            if d not in EXCLUDED_DIRS
            and not (not include_archive and d == "史料" and current_path == root)
            and not (d == "_generated" and current_path.name == "docs-next")
        ]
        for filename in filenames:
            path = current_path / filename
            if path.suffix not in suffixes:
                continue
            if tracked is not None and rel(path, root) not in tracked:
                continue
            if should_skip(path, root, include_archive):
                continue
            out.append(path)
    return sorted(out, key=lambda p: rel(p, root))


def line_count(text: str) -> int:
    return len(text.splitlines())


def title_from_markdown(text: str, fallback: str) -> str:
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else fallback


def first_paragraph(text: str) -> str:
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("```") and not s.startswith("|"):
            return s
    return ""


def md_table(headers: list[str], rows: Iterable[list[object]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(c).replace("\n", " ") for c in row) + " |")
    return "\n".join(out) + "\n"


def provenance(title: str, sources: list[str]) -> str:
    source_line = ", ".join(f"`{s}`" for s in sources[:8])
    if len(sources) > 8:
        source_line += f", ... ({len(sources)} total)"
    return (
        f"# {title}\n\n"
        "> DO NOT EDIT BY HAND. Generated by `python3 scripts/docs_next.py build`.\n"
        f"> Sources: {source_line or '`repo discovery`'}.\n\n"
    )


def module_name(path: Path, root: Path) -> str:
    r = rel(path, root)
    if r == "formal/SSBX.lean":
        return "SSBX"
    if r.startswith("formal/") and r.endswith(".lean"):
        return r[len("formal/") : -len(".lean")].replace("/", ".")
    return r


def lean_cluster(path: Path, root: Path) -> str:
    r = rel(path, root)
    parts = r.split("/")
    if r in {"formal/SSBX.lean", "formal/SSBX/Core.lean", "formal/SSBX/Roster.lean"}:
        return "root"
    if len(parts) >= 3 and parts[:2] == ["formal", "SSBX"]:
        if parts[2] == "Foundation" and len(parts) >= 4:
            return f"Foundation/{parts[3]}"
        return parts[2]
    return "other"


def lean_index(root: Path) -> tuple[dict, str]:
    records = []
    for path in files(root, (".lean",), include_archive=False):
        text = read(path)
        imports = re.findall(r"^import\s+(.+)$", text, re.MULTILINE)
        decls = [{"kind": k, "name": n} for k, n in DECL_RE.findall(text)]
        records.append(
            {
                "path": rel(path, root),
                "module": module_name(path, root),
                "cluster": lean_cluster(path, root),
                "imports": imports,
                "declaration_count": len(decls),
                "declarations": decls,
                "lines": line_count(text),
                "sha256": sha256_file(path),
            }
        )

    clusters: dict[str, int] = {}
    for record in records:
        clusters[record["cluster"]] = clusters.get(record["cluster"], 0) + 1

    md = provenance("Lean Module Index", [r["path"] for r in records])
    md += f"- Lean files: {len(records)}\n"
    md += f"- Clusters: {len(clusters)}\n\n"
    md += "## Clusters\n\n"
    md += md_table(["Cluster", "Files"], sorted(clusters.items()))
    md += "## Modules\n\n"
    md += md_table(
        ["Module", "Cluster", "Imports", "Decls", "Lines", "Path"],
        [
            [
                r["module"],
                r["cluster"],
                len(r["imports"]),
                r["declaration_count"],
                r["lines"],
                f"`{r['path']}`",
            ]
            for r in records
        ],
    )
    return {"records": records, "clusters": clusters}, md


def extract_inductive_names(text: str, type_name: str) -> list[str]:
    marker = f"inductive {type_name} where"
    if marker not in text:
        return []
    block = text.split(marker, 1)[1].split("deriving", 1)[0]
    out: list[str] = []
    for line in block.splitlines():
        s = line.strip()
        if not s.startswith("|"):
            continue
        for part in [p.strip() for p in s[1:].split("|") if p.strip()]:
            m = re.match(r"«([^»]+)»|([A-Za-z0-9_]+)", part)
            if m:
                out.append(m.group(1) or m.group(2))
    return out


def extract_case_list(block: str, target_kind: str) -> list[dict]:
    rows = []
    for name, rhs in re.findall(r"\| \.«([^»]+)» => \[(.*?)\]", block):
        refs = re.findall(r"([AGRPU]) \.«([^»]+)»", rhs)
        rows.append({"kind": target_kind, "name": name, "refs": [{"kind": k, "name": n} for k, n in refs]})
    return rows


def registry_index(root: Path) -> tuple[dict, str]:
    roster_path = root / "formal/SSBX/Roster.lean"
    text = read(roster_path)
    groups = {
        "atom": extract_inductive_names(text, "AtomName"),
        "generated": extract_inductive_names(text, "GenName"),
        "primitive": extract_inductive_names(text, "PrimName"),
        "recursive": extract_inductive_names(text, "RecName"),
        "pending": extract_inductive_names(text, "PendingName"),
    }

    roots_block = text.split("def rootsOfGenerated", 1)[1].split("def depsOfGenerated", 1)[0]
    deps_block = text.split("def depsOfGenerated", 1)[1].split("def recDeps", 1)[0]
    rec_block = text.split("def recDeps", 1)[1].split("def recSemantics", 1)[0]
    generated_roots = extract_case_list(roots_block, "generated")
    generated_deps = extract_case_list(deps_block, "generated")
    recursive_deps = extract_case_list(rec_block, "recursive")

    data = {
        "source": rel(roster_path, root),
        "counts": {k: len(v) for k, v in groups.items()},
        "groups": groups,
        "generated_roots": generated_roots,
        "generated_deps": generated_deps,
        "recursive_deps": recursive_deps,
    }

    md = provenance("Registry Index", [rel(roster_path, root)])
    md += md_table(["Kind", "Count"], data["counts"].items())
    md += "## Pending Interfaces\n\n"
    md += ", ".join(f"`{x}`" for x in groups["pending"]) + "\n\n"
    md += "## Recursive Items\n\n"
    md += ", ".join(f"`{x}`" for x in groups["recursive"]) + "\n"
    return data, md


def lean_cases_map(text: str, def_name: str) -> dict[str, str]:
    if f"def {def_name}" not in text:
        return {}
    block = text.split(f"def {def_name}", 1)[1]
    nxt = re.search(r"\n(?:def|theorem|instance|end)\s+", block)
    if nxt:
        block = block[: nxt.start()]
    out = {name: value for name, value in re.findall(r"\| \.([A-Za-z0-9_]+) => \"([^\"]*)\"", block)}
    out.update({name: value for name, value in re.findall(r"\| \.([A-Za-z0-9_]+) => \.([A-Za-z0-9_]+)", block)})
    return out


def lean_namespace_cases_map(text: str, namespace: str, def_name: str) -> dict[str, str]:
    marker = f"namespace {namespace}"
    if marker not in text:
        return {}
    block = text.split(marker, 1)[1]
    end_marker = f"end {namespace}"
    if end_marker in block:
        block = block.split(end_marker, 1)[0]
    return lean_cases_map(block, def_name)


def claim_index(root: Path) -> tuple[dict, str]:
    path = root / "formal/SSBX/Truth/ClaimLedger.lean"
    text = read(path)
    rows = []
    pattern = re.compile(
        r"\| \.([A-Za-z0-9_]+) => \{ id := \.[^,]+, label := \"([^\"]+)\", "
        r"kind := \.([A-Za-z0-9_]+), status := \.([A-Za-z0-9_]+), sourceRef := \"([^\"]+)\" \}"
    )
    for claim_id, label, kind, status, source_ref in pattern.findall(text):
        rows.append(
            {
                "id": claim_id,
                "label": label,
                "kind": kind,
                "status": status,
                "sourceRef": source_ref,
            }
        )
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    data = {"source": rel(path, root), "counts_by_status": counts, "claims": rows}
    md = provenance("Claim Index", [rel(path, root)])
    md += md_table(["Status", "Count"], sorted(counts.items()))
    md += "\n## Claims\n\n"
    md += md_table(["Id", "Label", "Kind", "Status", "Source"], [[r["id"], r["label"], r["kind"], r["status"], r["sourceRef"]] for r in rows])
    return data, md


def operator_index(root: Path) -> tuple[dict, str]:
    path = root / "formal/SSBX/Text/WenyanOperators.lean"
    text = read(path)
    groups = lean_cases_map(text, "OperatorId.group")
    group_keys = lean_cases_map(text, "OperatorGroup.key")
    group_names = lean_cases_map(text, "OperatorGroup.zhName")
    group_positions = lean_cases_map(text, "OperatorGroup.actionPosition")
    codes = lean_cases_map(text, "OperatorId.code")
    titles = lean_cases_map(text, "OperatorId.title")
    ids = extract_inductive_names(text, "OperatorId")

    sig_path = root / "formal/SSBX/Text/OperatorSignatures.lean"
    sig_text = read(sig_path)
    signature_keys = lean_cases_map(sig_text, "SignatureKind.key")
    signature_names = lean_cases_map(sig_text, "SignatureKind.zhName")
    signature_action_bits = lean_cases_map(sig_text, "SignatureKind.actionBit")
    action_keys = lean_cases_map(sig_text, "OperatorActionBit.key")
    action_names = lean_cases_map(sig_text, "OperatorActionBit.zhName")
    action_modes = lean_cases_map(sig_text, "OperatorActionBit.operatorMode")
    action_effects = lean_cases_map(sig_text, "OperatorActionBit.effectSummary")
    signatures = {
        op_id: {"signature_kind": kind, "arity": int(arity), "signature_evidence": "catalogueShape"}
        for op_id, kind, arity in re.findall(r"\| \.([A-Za-z0-9_]+) => \(\.([A-Za-z0-9_]+),\s*(\d+)\)", sig_text)
    }
    for op_id, kind, arity in re.findall(
        r"\{\s*id := \.([A-Za-z0-9_]+),\s+kind := \.([A-Za-z0-9_]+),\s+arity := (\d+)",
        sig_text,
    ):
        signatures[op_id] = {"signature_kind": kind, "arity": int(arity), "signature_evidence": "seedOverride"}

    rows = [
        {
            "id": i,
            "code": codes.get(i, ""),
            "group": groups.get(i, ""),
            "group_key": group_keys.get(groups.get(i, ""), ""),
            "group_name": group_names.get(groups.get(i, ""), ""),
            "action_position": group_positions.get(groups.get(i, ""), ""),
            "signature_kind": signatures.get(i, {}).get("signature_kind", ""),
            "signature_key": signature_keys.get(signatures.get(i, {}).get("signature_kind", ""), ""),
            "signature_name": signature_names.get(signatures.get(i, {}).get("signature_kind", ""), ""),
            "arity": signatures.get(i, {}).get("arity", ""),
            "signature_evidence": signatures.get(i, {}).get("signature_evidence", ""),
            "title": titles.get(i, ""),
        }
        for i in ids
    ]
    for row in rows:
        action_bit = signature_action_bits.get(row["signature_kind"], "")
        row["action_bit"] = action_bit
        row["action_key"] = action_keys.get(action_bit, "")
        row["action_name"] = action_names.get(action_bit, "")
        row["operator_mode"] = action_modes.get(action_bit, "")
        row["effect"] = action_effects.get(action_bit, "")
        sig_code = f"{row['signature_key']}{row['arity']}" if row["signature_key"] and row["arity"] != "" else ""
        row["full_code"] = ".".join(x for x in [row["group_key"], sig_code, row["action_key"], row["code"]] if x)
    counts: dict[str, int] = {}
    signature_counts: dict[str, int] = {}
    action_counts: dict[str, int] = {}
    action_signatures: dict[str, set[str]] = {}
    for row in rows:
        counts[row["group"]] = counts.get(row["group"], 0) + 1
        signature_counts[row["signature_kind"]] = signature_counts.get(row["signature_kind"], 0) + 1
        action_counts[row["action_bit"]] = action_counts.get(row["action_bit"], 0) + 1
        action_signatures.setdefault(row["action_bit"], set()).add(row["signature_kind"])
    group_rows = [
        {
            "group": group,
            "group_key": group_keys.get(group, ""),
            "group_name": group_names.get(group, ""),
            "action_position": group_positions.get(group, ""),
            "count": count,
        }
        for group, count in sorted(counts.items())
    ]
    signature_rows = [
        {
            "signature_kind": kind,
            "signature_key": signature_keys.get(kind, ""),
            "signature_name": signature_names.get(kind, ""),
            "count": count,
        }
        for kind, count in sorted(signature_counts.items())
    ]
    action_rows = [
        {
            "action_bit": bit,
            "action_key": action_keys.get(bit, ""),
            "action_name": action_names.get(bit, ""),
            "operator_mode": action_modes.get(bit, ""),
            "effect": action_effects.get(bit, ""),
            "signature_kinds": sorted(action_signatures.get(bit, set())),
            "count": count,
        }
        for bit, count in sorted(action_counts.items())
    ]
    data = {
        "source": rel(path, root),
        "signature_source": rel(sig_path, root),
        "count": len(rows),
        "groups": group_rows,
        "signature_kinds": signature_rows,
        "action_bits": action_rows,
        "counts_by_group": counts,
        "counts_by_signature_kind": signature_counts,
        "counts_by_action_bit": action_counts,
        "operators": rows,
    }
    md = provenance("Wenyan Operator Index", [rel(path, root), rel(sig_path, root), "wenyan-operators.md"])
    md += f"- Operators: {len(rows)}\n\n"
    md += md_table(
        ["Group", "Key", "Name", "Action Position", "Count"],
        [[r["group"], r["group_key"], r["group_name"], r["action_position"], r["count"]] for r in group_rows],
    )
    md += "\n## Signature Kinds\n\n"
    md += md_table(
        ["Kind", "Key", "Name", "Count"],
        [[r["signature_kind"], r["signature_key"], r["signature_name"], r["count"]] for r in signature_rows],
    )
    md += "\n## Action Bits\n\n"
    md += md_table(
        ["Bit", "Key", "Name", "Operator Mode", "Effect", "Signatures", "Count"],
        [
            [
                r["action_bit"],
                r["action_key"],
                r["action_name"],
                r["operator_mode"],
                r["effect"],
                ", ".join(r["signature_kinds"]),
                r["count"],
            ]
            for r in action_rows
        ],
    )
    md += "\n## Operators\n\n"
    md += md_table(
        [
            "Full Code",
            "Code",
            "Group",
            "Group Key",
            "Action Position",
            "Signature",
            "Sig Key",
            "Arity",
            "Action Bit",
            "Operator Mode",
            "Effect",
            "Title",
            "Id",
        ],
        [
            [
                r["full_code"],
                r["code"],
                r["group"],
                r["group_key"],
                r["action_position"],
                r["signature_kind"],
                r["signature_key"],
                r["arity"],
                r["action_name"],
                r["operator_mode"],
                r["effect"],
                r["title"],
                r["id"],
            ]
            for r in rows
        ],
    )
    return data, md


def cell192_transition_index(root: Path) -> tuple[dict, str]:
    cell_path = root / "formal/SSBX/Foundation/Bagua/Cell192.lean"
    reach_path = root / "formal/SSBX/Text/OperatorReachabilitySemantics.lean"
    reach_text = read(reach_path)

    operator_order = [
        "flip1",
        "flip2",
        "flip3",
        "flip4",
        "flip5",
        "flip6",
        "shiNext",
        "shiPrev",
        "hexCuo",
        "hexZong",
        "hexHu",
    ]
    operator_keys = lean_namespace_cases_map(reach_text, "Cell192TransitionOperator", "key")
    operator_names = lean_namespace_cases_map(reach_text, "Cell192TransitionOperator", "zhName")
    operator_refs = lean_namespace_cases_map(reach_text, "Cell192TransitionOperator", "operatorRef")
    operator_effects = lean_namespace_cases_map(reach_text, "Cell192TransitionOperator", "effectSummary")
    operators = [
        {
            "id": op,
            "key": operator_keys.get(op, ""),
            "name": operator_names.get(op, ""),
            "operator_ref": operator_refs.get(op, ""),
            "effect": operator_effects.get(op, ""),
        }
        for op in operator_order
    ]

    yaos = [("yang", "1", "阳"), ("yin", "0", "阴")]
    shis = [("ji", "JI", "已"), ("jin", "JIN", "今"), ("wei", "WEI", "未")]
    shi_next = {"JI": "JIN", "JIN": "WEI", "WEI": "JI"}
    shi_prev = {"JI": "WEI", "JIN": "JI", "WEI": "JIN"}

    cells = []
    index_by_code: dict[str, int] = {}
    for y1 in yaos:
        for y2 in yaos:
            for y3 in yaos:
                for y4 in yaos:
                    for y5 in yaos:
                        for y6 in yaos:
                            bits = "".join(y[1] for y in [y1, y2, y3, y4, y5, y6])
                            hex_label = "".join(y[2] for y in [y1, y2, y3, y4, y5, y6])
                            for _, shi_key, shi_label in shis:
                                code = f"H{bits}.{shi_key}"
                                row = {
                                    "index": len(cells) + 1,
                                    "cell": code,
                                    "hex_bits": bits,
                                    "hex_label": hex_label,
                                    "shi": shi_key,
                                    "shi_label": shi_label,
                                    "label": f"{hex_label}/{shi_label}",
                                }
                                index_by_code[code] = row["index"]
                                cells.append(row)

    def toggle(bit: str) -> str:
        return "0" if bit == "1" else "1"

    def apply_operator(bits: str, shi: str, operator: str) -> tuple[str, str]:
        if operator.startswith("flip"):
            pos = int(operator[-1]) - 1
            out = list(bits)
            out[pos] = toggle(out[pos])
            return "".join(out), shi
        if operator == "shiNext":
            return bits, shi_next[shi]
        if operator == "shiPrev":
            return bits, shi_prev[shi]
        if operator == "hexCuo":
            return "".join(toggle(bit) for bit in bits), shi
        if operator == "hexZong":
            return bits[::-1], shi
        if operator == "hexHu":
            return "".join([bits[1], bits[2], bits[3], bits[2], bits[3], bits[4]]), shi
        raise ValueError(f"unknown Cell192 transition operator: {operator}")

    transitions = []
    matrix_rows = []
    for cell in cells:
        targets = {}
        for operator in operators:
            to_bits, to_shi = apply_operator(cell["hex_bits"], cell["shi"], operator["id"])
            to_cell = f"H{to_bits}.{to_shi}"
            transitions.append(
                {
                    "from_index": cell["index"],
                    "from": cell["cell"],
                    "operator": operator["id"],
                    "operator_key": operator["key"],
                    "operator_name": operator["name"],
                    "operator_ref": operator["operator_ref"],
                    "effect": operator["effect"],
                    "to_index": index_by_code[to_cell],
                    "to": to_cell,
                }
            )
            targets[operator["id"]] = to_cell
        matrix_rows.append(
            {
                "from_index": cell["index"],
                "from": cell["cell"],
                "label": cell["label"],
                "targets": targets,
            }
        )

    data = {
        "sources": [rel(cell_path, root), rel(reach_path, root)],
        "coordinate_convention": "Habcdef.SHI uses six yao bits from bottom to top; 1=yang, 0=yin; SHI is JI/JIN/WEI.",
        "cell_count": len(cells),
        "operator_count": len(operators),
        "transition_count": len(transitions),
        "cells": cells,
        "operators": operators,
        "reachability_generator_ids": ["flip1", "flip2", "flip3", "flip4", "flip5", "flip6", "shiNext"],
        "transitions": transitions,
        "matrix": matrix_rows,
    }

    md = provenance("Cell192 Transition Index", data["sources"])
    md += f"- Cells: {len(cells)}\n"
    md += f"- Operators: {len(operators)}\n"
    md += f"- One-step transitions: {len(transitions)}\n"
    md += "- Reachability generators: `flip1`, `flip2`, `flip3`, `flip4`, `flip5`, `flip6`, `shiNext`.\n"
    md += "- Convention: `Habcdef.SHI` records six yao from bottom to top; `1=yang`, `0=yin`; `SHI ∈ {JI,JIN,WEI}`.\n\n"
    md += "## Operators\n\n"
    md += md_table(
        ["Id", "Key", "Name", "Lean Operator", "Effect"],
        [[op["id"], op["key"], op["name"], f"`{op['operator_ref']}`", op["effect"]] for op in operators],
    )
    md += "\n## Transition Matrix\n\n"
    headers = ["#", "From", "Label"] + [f"{op['key']} {op['name']}" for op in operators]
    md += md_table(
        headers,
        [
            [r["from_index"], r["from"], r["label"]] + [r["targets"][op["id"]] for op in operators]
            for r in matrix_rows
        ],
    )
    return data, md


def cell192_tree_index(root: Path) -> tuple[dict, str]:
    yi_path = root / "formal/SSBX/Foundation/Yi/Yi.lean"
    cell_path = root / "formal/SSBX/Foundation/Bagua/Cell192.lean"

    bits = [("1", "阳"), ("0", "阴")]
    shis = [("JI", "已"), ("JIN", "今"), ("WEI", "未")]
    position_names = ["初爻", "二爻", "三爻", "四爻", "五爻", "上爻"]

    def bit_label(bit_string: str) -> str:
        return "".join("阳" if bit == "1" else "阴" for bit in bit_string)

    def patterns(width: int) -> list[str]:
        return ["".join(p) for p in itertools.product([b[0] for b in bits], repeat=width)]

    nodes = [
        {
            "id": "ROOT",
            "level": 0,
            "kind": "root",
            "label": "根",
            "path": "根",
            "count_under_node": 192,
        }
    ]
    edges = []
    leaves = []

    for depth in range(1, 6):
        for prefix in patterns(depth):
            nodes.append(
                {
                    "id": f"Y{depth}.{prefix}",
                    "level": depth,
                    "kind": "yaoPrefix",
                    "label": bit_label(prefix),
                    "path": " / ".join(
                        f"{position_names[i]}={bit_label(prefix[i])}" for i in range(depth)
                    ),
                    "count_under_node": (2 ** (6 - depth)) * 3,
                }
            )

    for hex_bits in patterns(6):
        nodes.append(
            {
                "id": f"H{hex_bits}",
                "level": 6,
                "kind": "hexagram",
                "label": bit_label(hex_bits),
                "path": " / ".join(
                    f"{position_names[i]}={bit_label(hex_bits[i])}" for i in range(6)
                ),
                "count_under_node": 3,
            }
        )
        for shi_key, shi_label in shis:
            cell_id = f"H{hex_bits}.{shi_key}"
            path_parts = [f"{position_names[i]}={bit_label(hex_bits[i])}" for i in range(6)]
            path_parts.append(f"时态={shi_label}")
            cell = {
                "id": cell_id,
                "level": 7,
                "kind": "cell192",
                "label": f"{bit_label(hex_bits)}/{shi_label}",
                "path": " / ".join(path_parts),
                "count_under_node": 1,
            }
            nodes.append(cell)
            leaves.append(cell)

    for bit, label in bits:
        edges.append(
            {
                "from": "ROOT",
                "to": f"Y1.{bit}",
                "relation": f"生{position_names[0]}={label}",
                "relation_kind": "chooseYao",
            }
        )

    for depth in range(1, 5):
        for prefix in patterns(depth):
            for bit, label in bits:
                child = prefix + bit
                edges.append(
                    {
                        "from": f"Y{depth}.{prefix}",
                        "to": f"Y{depth + 1}.{child}",
                        "relation": f"定{position_names[depth]}={label}",
                        "relation_kind": "chooseYao",
                    }
                )

    for prefix in patterns(5):
        for bit, label in bits:
            hex_bits = prefix + bit
            edges.append(
                {
                    "from": f"Y5.{prefix}",
                    "to": f"H{hex_bits}",
                    "relation": f"定{position_names[5]}={label}; 成卦",
                    "relation_kind": "completeHexagram",
                }
            )

    for hex_bits in patterns(6):
        for shi_key, shi_label in shis:
            edges.append(
                {
                    "from": f"H{hex_bits}",
                    "to": f"H{hex_bits}.{shi_key}",
                    "relation": f"配时态={shi_label}; 成Cell192",
                    "relation_kind": "realizeShi",
                }
            )

    level_rows = [
        {"level": 0, "kind": "root", "count": 1, "meaning": "共同根节点"},
        {"level": 1, "kind": "yaoPrefix", "count": 2, "meaning": "初爻二分"},
        {"level": 2, "kind": "yaoPrefix", "count": 4, "meaning": "初、二爻前缀"},
        {"level": 3, "kind": "yaoPrefix", "count": 8, "meaning": "三爻前缀 / 八卦形"},
        {"level": 4, "kind": "yaoPrefix", "count": 16, "meaning": "四爻前缀"},
        {"level": 5, "kind": "yaoPrefix", "count": 32, "meaning": "五爻前缀"},
        {"level": 6, "kind": "hexagram", "count": 64, "meaning": "六爻成卦"},
        {"level": 7, "kind": "cell192", "count": 192, "meaning": "每卦配 已/今/未 三时态"},
    ]
    relation_rows = [
        {
            "kind": "chooseYao",
            "meaning": "在下一爻位选择阳或阴，沿二叉前缀树下行。",
            "edge_count": 2 + 4 + 8 + 16 + 32,
        },
        {
            "kind": "completeHexagram",
            "meaning": "选择上爻后，六位前缀闭合为一个 Hexagram。",
            "edge_count": 64,
        },
        {
            "kind": "realizeShi",
            "meaning": "每个 Hexagram 与 已/今/未 三时态相乘，成为 Cell192。",
            "edge_count": 192,
        },
    ]

    data = {
        "sources": [rel(yi_path, root), rel(cell_path, root)],
        "coordinate_convention": "Habcdef.SHI uses six yao bits from bottom to top; 1=yang, 0=yin; SHI is JI/JIN/WEI.",
        "shape": "1 -> 2 -> 4 -> 8 -> 16 -> 32 -> 64 -> 192",
        "node_count": len(nodes),
        "edge_count": len(edges),
        "leaf_count": len(leaves),
        "levels": level_rows,
        "relation_types": relation_rows,
        "nodes": nodes,
        "edges": edges,
        "leaves": leaves,
    }

    md = provenance("Cell192 Root Tree Index", data["sources"])
    md += f"- Shape: `{data['shape']}`\n"
    md += f"- Nodes: {len(nodes)}\n"
    md += f"- Edges: {len(edges)}\n"
    md += f"- Leaves: {len(leaves)}\n"
    md += "- Convention: `Habcdef.SHI` records six yao from bottom to top; `1=yang`, `0=yin`; `SHI ∈ {JI,JIN,WEI}`.\n\n"
    md += "## Levels\n\n"
    md += md_table(
        ["Level", "Kind", "Count", "Meaning"],
        [[r["level"], r["kind"], r["count"], r["meaning"]] for r in level_rows],
    )
    md += "\n## Relation Types\n\n"
    md += md_table(
        ["Kind", "Edges", "Meaning"],
        [[r["kind"], r["edge_count"], r["meaning"]] for r in relation_rows],
    )
    md += "\n## Tree Edges\n\n"
    md += md_table(
        ["From", "Relation", "To", "Kind"],
        [[r["from"], r["relation"], r["to"], r["relation_kind"]] for r in edges],
    )
    md += "\n## Leaf Paths\n\n"
    md += md_table(
        ["Cell", "Label", "Path"],
        [[r["id"], r["label"], r["path"]] for r in leaves],
    )
    return data, md


def markdown_index(root: Path, include_archive: bool) -> tuple[dict, str]:
    rows = []
    for path in files(root, (".md", ".mdx", ".rst", ".adoc"), include_archive=include_archive):
        text = read(path)
        headings = re.findall(r"^(#{1,6})\s+(.+)$", text, re.MULTILINE)
        links = re.findall(r"\[[^\]]+\]\(([^)]+)\)", text)
        rows.append(
            {
                "path": rel(path, root),
                "title": title_from_markdown(text, path.stem),
                "summary": first_paragraph(text),
                "lines": line_count(text),
                "headings": [{"level": len(h[0]), "title": h[1].strip()} for h in headings],
                "links": links,
                "sha256": sha256_file(path),
            }
        )
    data = {"include_archive": include_archive, "count": len(rows), "documents": rows}
    md = provenance("Markdown Index", [r["path"] for r in rows])
    md += f"- Markdown-like files indexed: {len(rows)}\n\n"
    md += md_table(["Title", "Lines", "Path"], [[r["title"], r["lines"], f"`{r['path']}`"] for r in rows])
    return data, md


def mermaid_counts(text: str) -> dict[str, int]:
    edge_matches = re.findall(r"^\s*[\w\u4e00-\u9fff]+\s+(?:[-.=]+>|---)", text, re.MULTILINE)
    node_matches = re.findall(r"^\s*[\w\u4e00-\u9fff]+(?:\[[^\]]+\]|\([^)]+\)|\{[^}]+\})", text, re.MULTILINE)
    return {"nodes": len(node_matches), "edges": len(edge_matches)}


def diagram_index(root: Path) -> tuple[dict, str]:
    rows = []
    for path in files(root, (".mmd",), include_archive=False):
        if "formal/SSBX/diagrams" not in rel(path, root):
            continue
        text = read(path)
        svg = path.with_suffix(".svg")
        rows.append(
            {
                "path": rel(path, root),
                "svg": rel(svg, root) if svg.exists() else "",
                "svg_exists": svg.exists(),
                "lines": line_count(text),
                **mermaid_counts(text),
                "sha256": sha256_file(path),
            }
        )
    data = {"count": len(rows), "diagrams": rows}
    md = provenance("Diagram Index", [r["path"] for r in rows])
    md += md_table(["Diagram", "SVG", "Nodes", "Edges", "Lines"], [[r["path"], r["svg"] or "missing", r["nodes"], r["edges"], r["lines"]] for r in rows])
    return data, md


def source_index(root: Path, include_archive: bool) -> dict:
    all_paths = []
    for suffixes in [(".lean",), (".md", ".mdx", ".rst", ".adoc"), (".mmd", ".svg", ".txt")]:
        for path in files(root, suffixes, include_archive=include_archive):
            all_paths.append(path)
    records = []
    for path in sorted(set(all_paths), key=lambda p: rel(p, root)):
        records.append(
            {
                "path": rel(path, root),
                "suffix": path.suffix,
                "bytes": path.stat().st_size,
                "sha256": sha256_file(path),
            }
        )
    return {"include_archive": include_archive, "count": len(records), "sources": records}


def crossrefs(root: Path, markdown_data: dict, lean_data: dict) -> tuple[dict, str]:
    lean_paths = {r["path"] for r in lean_data["records"]}
    lean_names: dict[str, list[str]] = {}
    for record in lean_data["records"]:
        for decl in record["declarations"]:
            lean_names.setdefault(decl["name"].strip("«»"), []).append(record["path"])

    rows = []
    for doc in markdown_data["documents"]:
        text = read(root / doc["path"])
        tokens = set(re.findall(r"`([^`]+)`", text))
        path_like = set(re.findall(r"(?:formal|scripts|web|义理|史料|六表_实虚史真)/[^\s`)，。；、]+", text))
        mentions = sorted({p for p in lean_paths if p in path_like or p in text})
        symbol_hits = []
        for name in sorted(tokens):
            lookup = name.strip("`").strip("«»")
            if lookup in lean_names:
                symbol_hits.append({"symbol": lookup, "paths": lean_names[lookup][:3]})
        rows.append({"document": doc["path"], "lean_path_mentions": mentions, "symbol_hits": symbol_hits[:20]})

    data = {"documents": rows}
    md = provenance("Cross References", ["Lean declarations", "Markdown documents"])
    md += md_table(
        ["Document", "Lean path mentions", "Symbol hits"],
        [[r["document"], len(r["lean_path_mentions"]), len(r["symbol_hits"])] for r in rows],
    )
    return data, md


def trust_boundary(root: Path) -> tuple[dict, str]:
    def code_lines_without_comments(text: str) -> list[str]:
        out: list[str] = []
        in_block = 0
        for line in text.splitlines():
            i = 0
            buf: list[str] = []
            while i < len(line):
                if in_block:
                    if line.startswith("-/", i):
                        in_block -= 1
                        i += 2
                    else:
                        i += 1
                    continue
                if line.startswith("/-", i):
                    in_block += 1
                    i += 2
                    continue
                if line.startswith("--", i):
                    break
                buf.append(line[i])
                i += 1
            out.append("".join(buf))
        return out

    rows = []
    for path in files(root, (".lean",), include_archive=False):
        text = read(path)
        for lineno, line in enumerate(code_lines_without_comments(text), start=1):
            s = line.strip()
            for kind, pattern in [
                ("axiom", r"^axiom\s+([^:\s]+)"),
                ("opaque", r"^opaque\s+([^:\s]+)"),
                ("partial def", r"^partial\s+def\s+([^(:=\s]+)"),
                ("unsafe", r"^unsafe\b"),
                ("sorry", r"^sorry\b"),
                ("admit", r"^admit\b"),
            ]:
                m = re.match(pattern, s)
                if m:
                    rows.append({"kind": kind, "name": m.group(1) if m.groups() else "", "path": rel(path, root), "line": lineno})
    data = {"records": rows}
    md = provenance("Trust Boundary Scan", ["formal/**/*.lean"])
    md += md_table(["Kind", "Name", "Path", "Line"], [[r["kind"], r["name"], f"`{r['path']}`", r["line"]] for r in rows])
    return data, md


def build_generated(root: Path, out: Path, include_archive: bool, web_payload: bool) -> list[GeneratedFile]:
    lean_data, lean_md = lean_index(root)
    registry_data, registry_md = registry_index(root)
    claim_data, claim_md = claim_index(root)
    operator_data, operator_md = operator_index(root)
    cell192_transition_data, cell192_transition_md = cell192_transition_index(root)
    cell192_tree_data, cell192_tree_md = cell192_tree_index(root)
    markdown_data, markdown_md = markdown_index(root, include_archive)
    diagram_data, diagram_md = diagram_index(root)
    crossrefs_data, crossrefs_md = crossrefs(root, markdown_data, lean_data)
    trust_data, trust_md = trust_boundary(root)
    sources = source_index(root, include_archive)

    payloads = {
        "sources": sources,
        "lean-index": lean_data,
        "registry-index": registry_data,
        "claim-index": claim_data,
        "operator-index": operator_data,
        "cell192-transition-index": cell192_transition_data,
        "cell192-tree-index": cell192_tree_data,
        "markdown-index": markdown_data,
        "diagram-index": diagram_data,
        "crossrefs": crossrefs_data,
        "trust-boundary": trust_data,
    }
    markdowns = {
        "lean-index": lean_md,
        "registry-index": registry_md,
        "claim-index": claim_md,
        "operator-index": operator_md,
        "cell192-transition-index": cell192_transition_md,
        "cell192-tree-index": cell192_tree_md,
        "markdown-index": markdown_md,
        "diagram-index": diagram_md,
        "crossrefs": crossrefs_md,
        "trust-boundary": trust_md,
    }

    generated: list[GeneratedFile] = []
    manifest_files = []
    for name, data in payloads.items():
        p = out / f"{name}.json"
        c = stable_json(data)
        generated.append(GeneratedFile(p, c))
        manifest_files.append({"path": rel(p, root), "sha256": sha256_text(c)})
    for name, content in markdowns.items():
        p = out / f"{name}.md"
        generated.append(GeneratedFile(p, content))
        manifest_files.append({"path": rel(p, root), "sha256": sha256_text(content)})

    if web_payload:
        web_data = {
            "meta": {"version": GENERATOR_VERSION, "rootName": root.name},
            "texts": markdown_data["documents"],
            "diagrams": diagram_data["diagrams"],
            "formal": lean_data["records"],
        }
        c = "window.SSBX_DATA = " + stable_json(web_data)
        generated.append(GeneratedFile(out / "web-data.js", c))
        manifest_files.append({"path": rel(out / "web-data.js", root), "sha256": sha256_text(c)})

    manifest = {
        "generator": GENERATOR_VERSION,
        "include_archive": include_archive,
        "generated_files": sorted(manifest_files, key=lambda r: r["path"]),
    }
    generated.append(GeneratedFile(out / "_manifest.json", stable_json(manifest)))
    return generated


def write_generated(files_to_write: list[GeneratedFile]) -> None:
    for item in files_to_write:
        item.path.parent.mkdir(parents=True, exist_ok=True)
        item.path.write_text(item.content, encoding="utf-8")


def clean_generated(out: Path) -> None:
    if out.exists():
        shutil.rmtree(out)


def compare_generated(root: Path, out: Path, generated: list[GeneratedFile]) -> list[str]:
    expected = {item.path.resolve(): item.content for item in generated}
    problems: list[str] = []
    for path, content in expected.items():
        if not path.exists():
            problems.append(f"missing generated file: {rel(path, root)}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != content:
            problems.append(f"stale generated file: {rel(path, root)}")
    if out.exists():
        for path in out.rglob("*"):
            if path.is_file() and path.resolve() not in expected:
                problems.append(f"extra generated file: {rel(path, root)}")
    return sorted(problems)


def check_links(root: Path) -> list[str]:
    problems: list[str] = []
    docs = root / "docs-next"
    if not docs.exists():
        return ["docs-next directory is missing"]
    for path in sorted(docs.rglob("*.md")):
        if DOCS_GENERATED_PART[1] in path.relative_to(root).parts:
            continue
        text = read(path)
        for target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", text):
            target = target.strip()
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            target = target.split("#", 1)[0]
            target = target.replace("%20", " ")
            resolved = (path.parent / target).resolve()
            if not resolved.exists():
                problems.append(f"broken link in {rel(path, root)} -> {target}")
    return problems


def cmd_build(args: argparse.Namespace) -> int:
    root = args.root.resolve()
    out = (root / args.out).resolve() if not args.out.is_absolute() else args.out
    generated = build_generated(root, out, args.include_archive, args.web_payload)
    if args.clean:
        clean_generated(out)
    write_generated(generated)
    print(f"wrote {len(generated)} generated files to {rel(out, root)}")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    root = args.root.resolve()
    out = (root / args.out).resolve() if not args.out.is_absolute() else args.out
    generated = build_generated(root, out, args.include_archive, args.web_payload)
    problems = compare_generated(root, out, generated)
    if args.strict:
        problems.extend(check_links(root))
        diagram_json = next((g for g in generated if g.path.name == "diagram-index.json"), None)
        if diagram_json:
            diagram_data = json.loads(diagram_json.content)
            for item in diagram_data["diagrams"]:
                if not item["svg_exists"]:
                    problems.append(f"missing diagram svg: {item['path']}")
    if problems:
        for p in sorted(problems):
            print(p)
        return 1
    print("docs-next generated files are current")
    return 0


def cmd_list_sources(args: argparse.Namespace) -> int:
    root = args.root.resolve()
    data = source_index(root, args.include_archive)
    for item in data["sources"]:
        print(item["path"])
    return 0


def cmd_clean(args: argparse.Namespace) -> int:
    root = args.root.resolve()
    out = (root / args.out).resolve() if not args.out.is_absolute() else args.out
    clean_generated(out)
    print(f"removed {rel(out, root)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    sub = parser.add_subparsers(dest="cmd", required=True)

    for name in ["build", "check", "list-sources", "clean"]:
        p = sub.add_parser(name)
        p.add_argument("--out", type=Path, default=DEFAULT_OUT)
        p.add_argument("--include-archive", action="store_true")
        p.add_argument("--web-payload", action="store_true")
        if name == "build":
            p.add_argument("--clean", action="store_true")
        if name == "check":
            p.add_argument("--strict", action="store_true")

    args = parser.parse_args(argv)
    if args.cmd == "build":
        return cmd_build(args)
    if args.cmd == "check":
        return cmd_check(args)
    if args.cmd == "list-sources":
        return cmd_list_sources(args)
    if args.cmd == "clean":
        return cmd_clean(args)
    raise AssertionError(args.cmd)


if __name__ == "__main__":
    sys.exit(main())
