#!/usr/bin/env python3
"""Generate Lean source files containing long `List YiInstr` literals
with automatic chunking, so IDE / Lean kernel can handle them.

Risk mitigated: 路径丙 § 风险 2 (Quine 字面展开破坏 IDE).

Usage:
    python3 scripts/gen_lean_literal.py \\
        --input  /path/to/instrs.json \\
        --output formal/SSBX/Foundation/Generated/MicrokernelSource.lean \\
        --module SSBX.Foundation.Generated.MicrokernelSource \\
        --name   微核源 \\
        --chunk-size 50

Input JSON shape (one of):

    {"instrs": [
        {"op": "nop"},
        {"op": "setShi", "arg": "wei"},
        {"op": "flipYao", "arg": 2},
        {"op": "branchYaoEq", "args": [2, 3, 5]},
        {"op": "jump", "arg": 7},
        ...
    ]}

The script:
  · groups instructions into chunks of `--chunk-size` (default 50);
  · emits one `def chunkN : List YiInstr := [...]` per chunk;
  · emits a master `def «<name>» : List YiInstr := chunk0 ++ chunk1 ++ ...`;
  · emits a `length` lemma proven by `native_decide`.

This forward-compatible scaffold is ready for M4-甲's quine engineering.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


# 12-instruction op vocabulary, matching YiInstr (BaguaTuring.lean §4).
NULLARY_OPS = {"nop", "hu", "cuo", "zong", "push", "pop", "halt"}
SHI_OPS = {"setShi"}                       # arg: "ji" | "jin" | "wei"
FIN6_OPS = {"flipYao"}                     # arg: 0..5
BRANCH_YAO_OPS = {"branchYaoEq"}           # args: [Fin 6, Fin 6, Nat]
BRANCH_SHI_OPS = {"branchShiEq"}           # args: [Shi, Nat]
JUMP_OPS = {"jump"}                        # arg: Nat


def render_shi(s: str) -> str:
    if s not in {"ji", "jin", "wei"}:
        raise ValueError(f"invalid Shi: {s!r}")
    return f"Shi.{s}"


def render_fin6(n: int) -> str:
    if not (0 <= n < 6):
        raise ValueError(f"Fin 6 out of range: {n}")
    return f"⟨{n}, by omega⟩"


def render_instr(instr: dict[str, Any]) -> str:
    op = instr["op"]
    if op in NULLARY_OPS:
        return f".{op}"
    if op in SHI_OPS:
        return f".{op} {render_shi(instr['arg'])}"
    if op in FIN6_OPS:
        return f".{op} {render_fin6(int(instr['arg']))}"
    if op in BRANCH_YAO_OPS:
        i, j, t = instr["args"]
        return f".{op} {render_fin6(int(i))} {render_fin6(int(j))} {int(t)}"
    if op in BRANCH_SHI_OPS:
        s, t = instr["args"]
        return f".{op} {render_shi(s)} {int(t)}"
    if op in JUMP_OPS:
        return f".{op} {int(instr['arg'])}"
    raise ValueError(f"unknown YiInstr op: {op!r}")


def chunk_list(xs: list[Any], size: int) -> list[list[Any]]:
    return [xs[i:i + size] for i in range(0, len(xs), size)]


HEADER = """\
/-
# {module} — auto-generated literal `List YiInstr`

DO NOT EDIT BY HAND.  Generated by `scripts/gen_lean_literal.py`.

Source: {input_path}
Total instructions: {total}
Chunk size: {chunk_size}
Number of chunks: {n_chunks}

Each chunk is a separate `def`, allowing `native_decide` to verify
properties chunk-by-chunk without exhausting the kernel reduction budget.
The master definition `«{name}»` concatenates all chunks.

Usage in proofs (combine via `ChunkedDecide.all_append`):
    theorem «{name}_well_formed» :
        «{name}».all isWellFormedInstr = true := by
      show ((chunk0 ++ chunk1) ++ ...).all _ = true
      simp only [ChunkedDecide.all_append]
      refine (by native_decide) -- chunk0
        |>.and (by native_decide) -- chunk1
        ...
-/
import SSBX.Foundation.BaguaTuring
import SSBX.Foundation.ChunkedDecide

namespace {namespace}

open SSBX.Foundation.Yi
open SSBX.Foundation.Cell192
open SSBX.Foundation.BaguaTuring

"""

FOOTER_TEMPLATE = """
/-- Auto-generated master definition. -/
def «{name}» : List YiInstr :=
  {concat}

/-- 长度由生成器记录。 -/
theorem «{name}_length» : («{name}»).length = {total} := by native_decide

end {namespace}
"""


def render_lean(instrs: list[dict], name: str, module: str,
                chunk_size: int, input_path: str) -> str:
    chunks = chunk_list(instrs, chunk_size)
    namespace = module
    lines = [HEADER.format(
        module=module,
        input_path=input_path,
        total=len(instrs),
        chunk_size=chunk_size,
        n_chunks=len(chunks),
        name=name,
        namespace=namespace,
    )]
    for idx, ch in enumerate(chunks):
        lines.append(f"/-- Chunk {idx} ({len(ch)} instructions). -/")
        lines.append(f"def chunk{idx} : List YiInstr := [")
        for k, inst in enumerate(ch):
            sep = "," if k < len(ch) - 1 else ""
            lines.append(f"  {render_instr(inst)}{sep}")
        lines.append("]\n")
        lines.append(f"theorem chunk{idx}_length : chunk{idx}.length = {len(ch)} := by native_decide\n")

    concat = " ++ ".join(f"chunk{i}" for i in range(len(chunks))) if chunks else "[]"
    lines.append(FOOTER_TEMPLATE.format(name=name, concat=concat,
                                        total=len(instrs), namespace=namespace))
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--input", required=True, help="JSON file with {instrs: [...]}")
    p.add_argument("--output", required=True, help="output .lean file path")
    p.add_argument("--module", required=True,
                   help="Lean namespace (e.g. SSBX.Foundation.Generated.X)")
    p.add_argument("--name", required=True,
                   help="literal name (Chinese OK; will be wrapped in «»)")
    p.add_argument("--chunk-size", type=int, default=50,
                   help="instructions per chunk (default: 50)")
    args = p.parse_args(argv)

    payload = json.loads(Path(args.input).read_text(encoding="utf-8"))
    instrs = payload["instrs"]
    if not isinstance(instrs, list):
        print("input.instrs must be a list", file=sys.stderr)
        return 1

    out = render_lean(instrs, args.name, args.module,
                      args.chunk_size, args.input)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {len(instrs)} instructions in "
          f"{(len(instrs) + args.chunk_size - 1) // args.chunk_size} chunks "
          f"to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
