#!/usr/bin/env python3
"""Generate position/operator graphs for the Yi/Bagua finite state layers.

Outputs:
- PositionOperatorGraph.six.mmd: six slot-level positions with operator edges.
- PositionOperatorGraph.hex64.mmd: all 64 hexagram states with operator edges.
- PositionOperatorGraph.md: audit notes and missing-edge interpretation.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIAGRAMS_DIR = ROOT / "formal/SSBX/diagrams"
NOTES_DIR = ROOT / "formal/SSBX/notes"

BITS = ("阳", "阴")


@dataclass(frozen=True)
class Edge:
    src: str
    dst: str
    label: str
    directed: bool = False


def bits(n: int) -> tuple[int, ...]:
    return tuple((n >> i) & 1 for i in range(6))


def bit_label(bs: tuple[int, ...]) -> str:
    # y1..y6, bottom to top. 0 = 阳, 1 = 阴.
    return "".join(BITS[b] for b in bs)


def bit_id(bs: tuple[int, ...]) -> str:
    return "h" + "".join(str(b) for b in bs)


def flip(bs: tuple[int, ...], i: int) -> tuple[int, ...]:
    out = list(bs)
    out[i] = 1 - out[i]
    return tuple(out)


def cuo(bs: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(1 - b for b in bs)


def zong(bs: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(reversed(bs))


def hu(bs: tuple[int, ...]) -> tuple[int, ...]:
    # Lean: ⟨h.y2, h.y3, h.y4, h.y3, h.y4, h.y5⟩
    return (bs[1], bs[2], bs[3], bs[2], bs[3], bs[4])


def mermaid_escape(label: str) -> str:
    return label.replace('"', '\\"')


def write_six_graph() -> None:
    nodes = {
        "p1": "初位 / y1",
        "p2": "二位 / y2",
        "p3": "三位 / y3",
        "p4": "四位 / y4",
        "p5": "五位 / y5",
        "p6": "上位 / y6",
    }
    edges = [
        Edge("p1", "p1", "flip1 / 错此位"),
        Edge("p2", "p2", "flip2 / 错此位"),
        Edge("p3", "p3", "flip3 / 错此位"),
        Edge("p4", "p4", "flip4 / 错此位"),
        Edge("p5", "p5", "flip5 / 错此位"),
        Edge("p6", "p6", "flip6 / 错此位"),
        Edge("p1", "p6", "综"),
        Edge("p2", "p5", "综"),
        Edge("p3", "p4", "综"),
        Edge("p1", "p4", "应位"),
        Edge("p2", "p5", "应位 / 中应"),
        Edge("p3", "p6", "应位"),
        Edge("p1", "p2", "比 / 承乘候选"),
        Edge("p2", "p3", "比 / 承乘候选"),
        Edge("p3", "p4", "比 / 承乘候选"),
        Edge("p4", "p5", "比 / 承乘候选"),
        Edge("p5", "p6", "比 / 承乘候选"),
        Edge("p2", "p1", "互: y2→y1", True),
        Edge("p3", "p2", "互: y3→y2", True),
        Edge("p4", "p3", "互: y4→y3", True),
        Edge("p3", "p4", "互: y3→y4", True),
        Edge("p4", "p5", "互: y4→y5", True),
        Edge("p5", "p6", "互: y5→y6", True),
    ]
    lines = [
        "%% Generated by scripts/generate_position_operator_graph.py.",
        "flowchart LR",
        "  %% Six-slot position graph. Solid edges are slot relations/operators; arrows show 互 output flow.",
    ]
    for node_id, label in nodes.items():
        lines.append(f'  {node_id}["{mermaid_escape(label)}"]')
    for edge in edges:
        arrow = "-->" if edge.directed else "---"
        lines.append(f'  {edge.src} {arrow}|"{mermaid_escape(edge.label)}"| {edge.dst}')
    lines.extend([
        "  classDef pos fill:#f8fafc,stroke:#64748b,color:#0f172a;",
        "  class p1,p2,p3,p4,p5,p6 pos;",
    ])
    (DIAGRAMS_DIR / "PositionOperatorGraph.six.mmd").write_text("\n".join(lines) + "\n")


def hex_edges() -> list[Edge]:
    states = [bits(n) for n in range(64)]
    out: list[Edge] = []
    seen: set[tuple[str, str, str]] = set()

    def add_undirected(a: tuple[int, ...], b: tuple[int, ...], label: str) -> None:
        ia, ib = bit_id(a), bit_id(b)
        src, dst = sorted([ia, ib])
        key = (src, dst, label)
        if key not in seen:
            seen.add(key)
            out.append(Edge(src, dst, label))

    for s in states:
        for i in range(6):
            add_undirected(s, flip(s, i), f"flip{i + 1}")
        add_undirected(s, cuo(s), "错")
        add_undirected(s, zong(s), "综")
        out.append(Edge(bit_id(s), bit_id(hu(s)), "互", True))
    return out


def connected_by_flips() -> tuple[bool, int]:
    states = [bits(n) for n in range(64)]
    start = states[0]
    seen = {start}
    q = deque([start])
    while q:
        s = q.popleft()
        for i in range(6):
            t = flip(s, i)
            if t not in seen:
                seen.add(t)
                q.append(t)
    return len(seen) == 64, len(seen)


def write_hex64_graph() -> None:
    states = [bits(n) for n in range(64)]
    lines = [
        "%% Generated by scripts/generate_position_operator_graph.py.",
        "flowchart LR",
        "  %% 64 hexagram states. Nodes are y1..y6 bit patterns, bottom to top.",
    ]
    for s in states:
        lines.append(f'  {bit_id(s)}["{mermaid_escape(bit_label(s))}"]')
    for edge in hex_edges():
        arrow = "-->" if edge.directed else "---"
        lines.append(f'  {edge.src} {arrow}|"{mermaid_escape(edge.label)}"| {edge.dst}')
    lines.extend([
        "  classDef hex fill:#ecfeff,stroke:#0891b2,color:#164e63;",
        "  class " + ",".join(bit_id(s) for s in states) + " hex;",
    ])
    (DIAGRAMS_DIR / "PositionOperatorGraph.hex64.mmd").write_text("\n".join(lines) + "\n")


def write_notes() -> None:
    connected, reached = connected_by_flips()
    md = [
        "# Position Operator Graph",
        "",
        "Generated by `scripts/generate_position_operator_graph.py`.",
        "",
        "## Files",
        "",
        "- `formal/SSBX/diagrams/PositionOperatorGraph.six.mmd`: six-slot position graph.",
        "- `formal/SSBX/diagrams/PositionOperatorGraph.hex64.mmd`: full 64-hexagram operator graph.",
        "",
        "## Audit Reading",
        "",
        f"- Six single-position flips reach `{reached}/64` hexagram states from any start; connected = `{str(connected).lower()}`.",
        "- Therefore the T6 bit-state layer has no missing lateral flip operator for reachability.",
        "- `错` is redundant for reachability because it is the composite of all six flips.",
        "- `综` is a position-reversal symmetry; it is not generated by single flips because it permutes slots rather than values.",
        "- `互` is directed and non-invertible: it drops y1/y6 and duplicates middle positions. It is a semantic extraction operator, not a reachability generator.",
        "- For `Cell192 = Hexagram × Shi`, hexagram edges alone split into three time components. A time operator (`shiNext`/`shiPrev`, or YiInstr `setShi`) is required for full 192-cell connectivity.",
        "",
        "## Missing-Operator Interpretation",
        "",
        "- Missing for T6 state reachability: none, given `flip1..flip6`.",
        "- Missing for full Cell192 reachability: none if the time edge is included; missing time connectivity if only hexagram operators are admitted.",
        "- Missing for full position-permutation algebra: adjacent swap or rotation is not primitive. Current code has `综` but no generator for arbitrary S6 permutations. This is only a gap if the intended operator set must cover all position permutations, not just Yi/Bagua state reachability.",
    ]
    (NOTES_DIR / "PositionOperatorGraph.md").write_text("\n".join(md) + "\n")


def main() -> None:
    DIAGRAMS_DIR.mkdir(parents=True, exist_ok=True)
    NOTES_DIR.mkdir(parents=True, exist_ok=True)
    write_six_graph()
    write_hex64_graph()
    write_notes()
    print(f"wrote {DIAGRAMS_DIR / 'PositionOperatorGraph.six.mmd'}")
    print(f"wrote {DIAGRAMS_DIR / 'PositionOperatorGraph.hex64.mmd'}")
    print(f"wrote {NOTES_DIR / 'PositionOperatorGraph.md'}")


if __name__ == "__main__":
    main()
