/-
# HistoryTapeStructure — 史带、算子列、爻根的结构骨架

This module narrows the informal claim:

  history is a tape-like list of cells; expressions are generated by operator
  lists over roots or over paired subexpressions; the root data are yao.

It proves only the typed skeleton already supported by the codebase.  It does
not claim a full denotation for every catalogue operator, nor a bi-infinite
Turing tape with a movable head.
-/
import SSBX.Foundation.Core.Yuan
import SSBX.Foundation.Atlas.YiLegacy.Bagua.BaguaTuring
import SSBX.Foundation.Atlas.YiLegacy.Bagua.BaguaAlgebra
import SSBX.Foundation.Modern.MingBoundary
import SSBX.Text.OperatorInstructionSemantics
import SSBX.Text.OperatorSignatures

namespace SSBX.Foundation.Modern.HistoryTapeStructure

open SSBX.Foundation.Yi.Yi
open SSBX.Foundation.Core.Yuan
open SSBX.Foundation.Bagua.R8
open SSBX.Foundation.Bagua.BaguaTuring
open SSBX.Foundation.Bagua.BaguaAlgebra
open SSBX.Foundation.Modern.MingBoundary
open SSBX.Text.WenyanOperators
open SSBX.Text.OperatorInstructionSemantics
open SSBX.Text.OperatorSignatures

/-! ## § 1 史带：YiState.history as an unbounded list -/

/-- The "史带" at the executable L0 layer is the `history` list of cells. -/
abbrev HistoryTape : Type := List R8

/-- Read the tape component from an interpreter state. -/
def stateTape (s : YiState) : HistoryTape :=
  s.history

theorem stateTape_eq_history (s : YiState) :
    stateTape s = s.history := rfl

theorem push_writes_current_cell_to_tape (s : YiState) :
    stateTape (YiState.execute YiInstr.push s) = s.cur :: stateTape s := by
  rfl

theorem pop_empty_halts (s : YiState) (h : stateTape s = []) :
    (YiState.execute YiInstr.pop s).halted = true := by
  cases s with
  | mk cur history pc prog halted =>
      simp [stateTape] at h
      subst history
      rfl

theorem pop_reads_head_cell_from_tape (s : YiState) (c : R8) (rest : HistoryTape)
    (h : stateTape s = c :: rest) :
    stateTape (YiState.execute YiInstr.pop s) = rest
      ∧ (YiState.execute YiInstr.pop s).cur = c := by
  cases s with
  | mk cur history pc prog halted =>
      simp [stateTape] at h
      subst history
      simp [YiState.execute, stateTape]

/-! ## § 2 爻根：cells bottom out in six Yuan/Yao values -/

/-- The yao trace carried by a 256-cell. -/
def cellYuanTrace (c : R8) : List Yuan :=
  c.1.toDuoYuan

theorem cellYuanTrace_length (c : R8) :
    (cellYuanTrace c).length = 6 := by
  rcases c with ⟨h, _s⟩
  exact hex_toDuoYuan_length h

theorem fen_three_yuan_makes_trigram (y1 y2 y3 : Yuan) :
    fenToTrigram (fenToSiXiang (fenToYi () y1) y2) y3 = ⟨y1, y2, y3⟩ := by
  rfl

/-- A direct six-yao constructor used to state the hexagram root trace. -/
def hexFromYuan (y1 y2 y3 y4 y5 y6 : Yuan) : Hexagram :=
  ⟨y1, y2, y3, y4, y5, y6⟩

theorem hexFromYuan_trace (y1 y2 y3 y4 y5 y6 : Yuan) :
    (hexFromYuan y1 y2 y3 y4 y5 y6).toDuoYuan =
      [y1, y2, y3, y4, y5, y6] := by
  rfl

/-! ## § 3 算子列递归结构：catalogue-level typed skeleton -/

/-- A catalogue-level operator sequence.  This is syntax-level, not a full denotation. -/
abbrev CatalogueOperatorSeq : Type := List OperatorId

/--
Recursive structure expression:

* `root y` is a single yao/root.
* `operatorList ops e` reads as 算子列(e).
* `combine ops l r` reads as 算子列(l, r).
-/
inductive StructureExpr where
  | root : Yuan → StructureExpr
  | operatorList : CatalogueOperatorSeq → StructureExpr → StructureExpr
  | combine : CatalogueOperatorSeq → StructureExpr → StructureExpr → StructureExpr
  deriving Repr

/-- Predicate saying every leaf of the expression is a yao/root. -/
def BuiltFromYao : StructureExpr → Prop
  | .root _ => True
  | .operatorList _ e => BuiltFromYao e
  | .combine _ l r => BuiltFromYao l ∧ BuiltFromYao r

def yaoLeafCount : StructureExpr → Nat
  | .root _ => 1
  | .operatorList _ e => yaoLeafCount e
  | .combine _ l r => yaoLeafCount l + yaoLeafCount r

theorem structureExpr_built_from_yao (e : StructureExpr) :
    BuiltFromYao e := by
  induction e with
  | root _ =>
      trivial
  | operatorList _ _ ih =>
      exact ih
  | combine _ _ _ ihl ihr =>
      exact ⟨ihl, ihr⟩

theorem yaoLeafCount_pos (e : StructureExpr) :
    0 < yaoLeafCount e := by
  induction e with
  | root _ =>
      exact Nat.zero_lt_one
  | operatorList _ _ ih =>
      exact ih
  | combine _ _ _ ihl _ =>
      exact Nat.add_pos_left ihl _

theorem structureExpr_exhaustive (e : StructureExpr) :
    (∃ y : Yuan, e = .root y)
      ∨ (∃ ops x, e = .operatorList ops x ∧ BuiltFromYao x)
      ∨ (∃ ops l r, e = .combine ops l r ∧ BuiltFromYao l ∧ BuiltFromYao r) := by
  cases e with
  | root y =>
      exact Or.inl ⟨y, rfl⟩
  | operatorList ops x =>
      exact Or.inr (Or.inl ⟨ops, x, rfl, structureExpr_built_from_yao x⟩)
  | combine ops l r =>
      exact Or.inr
        (Or.inr
          ⟨ops, l, r, rfl, structureExpr_built_from_yao l, structureExpr_built_from_yao r⟩)

theorem operatorList_root_form (ops : CatalogueOperatorSeq) (y : Yuan) :
    BuiltFromYao (.operatorList ops (.root y)) := by
  trivial

theorem operatorList_binary_form
    (ops outerOpsL outerOpsR : CatalogueOperatorSeq) (left right : Yuan) :
    BuiltFromYao
      (.combine ops
        (.operatorList outerOpsL (.root left))
        (.operatorList outerOpsR (.root right))) := by
  exact ⟨trivial, trivial⟩

/-! ## § 4 分/和 roles: operators distinguish; names bind -/

/-- The two structural roles needed here: 分 distinguishes, 和 binds. -/
inductive StructureAct where
  | fen
  | he
  deriving Repr, DecidableEq

/-- In this interface, an operator sequence is read as 分: it makes distinctions. -/
def operatorSeqAct (_ops : CatalogueOperatorSeq) : StructureAct :=
  .fen

/-- In this interface, a name is read as 和: it binds naming axes together. -/
def nameAct (_m : MingSkeleton) : StructureAct :=
  .he

/-- Apply an operator sequence to an expression as a structural 分 layer. -/
def splitByOperators (ops : CatalogueOperatorSeq) (e : StructureExpr) : StructureExpr :=
  .operatorList ops e

/-- A named structure: a body together with the naming skeleton that binds it. -/
structure NamedStructure where
  name : MingSkeleton
  body : StructureExpr
  deriving Repr

def namedByHe (name : MingSkeleton) (body : StructureExpr) : NamedStructure :=
  { name, body }

def WellFormedNamedStructure (ns : NamedStructure) : Prop :=
  CompleteMing ns.name ∧ BuiltFromYao ns.body

theorem operator_sequences_are_fen (ops : CatalogueOperatorSeq) :
    operatorSeqAct ops = .fen := rfl

theorem names_are_he (m : MingSkeleton) :
    nameAct m = .he := rfl

/--
分(和) expresses a structure, in the narrow typed-skeleton sense:
operator sequences provide the 分 role, naming skeletons provide the 和 role,
and complete names attached to yao-built expressions remain well formed.
-/
theorem fen_he_expresses_structure
    (ops : CatalogueOperatorSeq) (name : MingSkeleton) (e : StructureExpr)
    (hname : CompleteMing name) :
    operatorSeqAct ops = .fen
      ∧ nameAct name = .he
      ∧ WellFormedNamedStructure (namedByHe name (splitByOperators ops e)) := by
  exact
    ⟨ operator_sequences_are_fen ops
    , names_are_he name
    , hname
    , structureExpr_built_from_yao (splitByOperators ops e)
    ⟩

/-! ## § 5 乾坤、一、元、爻 and 上/中/下 layers -/

/-- The unique "一" root used before a yao distinction is introduced. -/
abbrev RootOne : Type := Unit

def rootOne : RootOne := ()

theorem root_one_unique (x : RootOne) :
    x = rootOne := by
  cases x
  rfl

/-- At this layer, 元 is definitionally 爻. -/
theorem yuan_is_yao :
    Yuan = Yao :=
  yuan_eq_yao

/-- 乾坤 at the root layer is the yang/yin pair of Yuan/Yao values. -/
def qianKunYuanPoles : Yuan × Yuan :=
  (Yao.yang, Yao.yin)

/-- 乾坤 at the trigram layer is the all-yang/all-yin pair. -/
def qianKunTrigrams : Trigram × Trigram :=
  (Trigram.heaven, Trigram.earth)

theorem qianKunYuanPoles_eq :
    qianKunYuanPoles = (Yao.yang, Yao.yin) := rfl

theorem qianKunTrigrams_eq :
    qianKunTrigrams = (Trigram.heaven, Trigram.earth) := rfl

/-- The three vertical layers of one trigram: 下 / 中 / 上. -/
inductive VerticalLayer where
  | xia
  | zhong
  | shang
  deriving Repr, DecidableEq

namespace VerticalLayer

def surface : VerticalLayer → String
  | .xia => "下"
  | .zhong => "中"
  | .shang => "上"

def rank : VerticalLayer → Nat
  | .xia => 0
  | .zhong => 1
  | .shang => 2

theorem exhaustive (l : VerticalLayer) :
    l = .xia ∨ l = .zhong ∨ l = .shang := by
  cases l <;> simp

end VerticalLayer

/-- Judge which layer a 0-indexed trigram yao position belongs to. -/
def layerOfTrigramIndex (i : Fin 3) : VerticalLayer :=
  if i.val = 0 then .xia
  else if i.val = 1 then .zhong
  else .shang

theorem layerOfTrigramIndex_complete (i : Fin 3) :
    layerOfTrigramIndex i = .xia
      ∨ layerOfTrigramIndex i = .zhong
      ∨ layerOfTrigramIndex i = .shang := by
  unfold layerOfTrigramIndex
  by_cases h0 : i.val = 0
  · simp [h0]
  · by_cases h1 : i.val = 1
    · simp [h1]
    · simp [h0, h1]

/-- Read the yao at a named vertical layer. -/
def layerYao (t : Trigram) : VerticalLayer → Yuan
  | .xia => t.y1
  | .zhong => t.y2
  | .shang => t.y3

theorem qian_kun_layers_differ (l : VerticalLayer) :
    layerYao Trigram.heaven l ≠ layerYao Trigram.earth l := by
  cases l <;> decide

theorem qian_layers_are_yang (l : VerticalLayer) :
    layerYao Trigram.heaven l = Yao.yang := by
  cases l <;> rfl

theorem kun_layers_are_yin (l : VerticalLayer) :
    layerYao Trigram.earth l = Yao.yin := by
  cases l <;> rfl

/-- Relations among the three vertical layers. -/
inductive LayerRelation where
  | same
  | adjacent
  | separated
  deriving Repr, DecidableEq

def layerRelation (a b : VerticalLayer) : LayerRelation :=
  match a, b with
  | .xia, .xia | .zhong, .zhong | .shang, .shang => .same
  | .xia, .zhong | .zhong, .xia
  | .zhong, .shang | .shang, .zhong => .adjacent
  | .xia, .shang | .shang, .xia => .separated

theorem lower_middle_adjacent :
    layerRelation .xia .zhong = .adjacent := rfl

theorem middle_upper_adjacent :
    layerRelation .zhong .shang = .adjacent := rfl

theorem lower_upper_separated :
    layerRelation .xia .shang = .separated := rfl

/-- Local readings of `间` needed by this file. -/
inductive JianReading where
  | betweenLayers
  | endpointInterval
  deriving Repr, DecidableEq

/--
In this module, `乾坤之间` is read as the between-ness of the three
vertical layers, not as an endpoint interval object.
-/
def qianKunJianReading : JianReading :=
  .betweenLayers

/-- The three layers displayed by the local `乾坤之间` reading. -/
def qianKunJianLayers : List VerticalLayer :=
  [.xia, .zhong, .shang]

theorem qianKunJianReading_is_between_layers :
    qianKunJianReading = .betweenLayers := rfl

theorem qianKunJianReading_not_endpoint_interval :
    qianKunJianReading ≠ .endpointInterval := by
  intro h
  cases h

theorem qianKunJianLayers_complete (l : VerticalLayer) :
    l ∈ qianKunJianLayers := by
  cases l <;> simp [qianKunJianLayers]

theorem qian_kun_jian_between_layers_summary :
    qianKunJianReading = .betweenLayers
      ∧ qianKunJianReading ≠ .endpointInterval
      ∧ (∀ l : VerticalLayer, l ∈ qianKunJianLayers)
      ∧ layerRelation .xia .zhong = .adjacent
      ∧ layerRelation .zhong .shang = .adjacent
      ∧ layerRelation .xia .shang = .separated := by
  exact
    ⟨ qianKunJianReading_is_between_layers
    , qianKunJianReading_not_endpoint_interval
    , qianKunJianLayers_complete
    , lower_middle_adjacent
    , middle_upper_adjacent
    , lower_upper_separated
    ⟩

/-- Existing 合 operators indexed by the layer being removed. -/
def removeLayer : VerticalLayer → Trigram → SiXiang
  | .xia, t => heXia t
  | .zhong, t => heZhong t
  | .shang, t => heShang t

/-- 分 inserts a yao at the chosen layer. -/
def fenAtLayer : VerticalLayer → SiXiang → Yuan → Trigram
  | .xia, s, y => ⟨y, s.y1, s.y2⟩
  | .zhong, s, y => ⟨s.y1, y, s.y2⟩
  | .shang, s, y => fenToTrigram s y

theorem removeLayer_fenAtLayer (l : VerticalLayer) (s : SiXiang) (y : Yuan) :
    removeLayer l (fenAtLayer l s y) = s := by
  cases l <;> cases s <;> rfl

theorem qian_kun_yuan_yao_layer_summary :
    (∀ x : RootOne, x = rootOne)
      ∧ Yuan = Yao
      ∧ qianKunYuanPoles = (Yao.yang, Yao.yin)
      ∧ qianKunTrigrams = (Trigram.heaven, Trigram.earth)
      ∧ (∀ l : VerticalLayer,
          layerYao Trigram.heaven l = Yao.yang ∧ layerYao Trigram.earth l = Yao.yin)
      ∧ (∀ l : VerticalLayer, layerYao Trigram.heaven l ≠ layerYao Trigram.earth l)
      ∧ qianKunJianReading = .betweenLayers
      ∧ qianKunJianReading ≠ .endpointInterval
      ∧ (∀ l : VerticalLayer, l ∈ qianKunJianLayers)
      ∧ (∀ i : Fin 3,
          layerOfTrigramIndex i = .xia
            ∨ layerOfTrigramIndex i = .zhong
            ∨ layerOfTrigramIndex i = .shang)
      ∧ layerRelation .xia .zhong = .adjacent
      ∧ layerRelation .zhong .shang = .adjacent
      ∧ layerRelation .xia .shang = .separated
      ∧ (∀ l : VerticalLayer, ∀ s : SiXiang, ∀ y : Yuan,
          removeLayer l (fenAtLayer l s y) = s) := by
  exact
    ⟨ root_one_unique
    , yuan_is_yao
    , qianKunYuanPoles_eq
    , qianKunTrigrams_eq
    , fun l => ⟨qian_layers_are_yang l, kun_layers_are_yin l⟩
    , qian_kun_layers_differ
    , qianKunJianReading_is_between_layers
    , qianKunJianReading_not_endpoint_interval
    , qianKunJianLayers_complete
    , layerOfTrigramIndex_complete
    , lower_middle_adjacent
    , middle_upper_adjacent
    , lower_upper_separated
    , removeLayer_fenAtLayer
    ⟩

/-! ## § 6 Public summary -/

/--
Machine-checkable summary of the narrow claim:

* `history` is a `List R8` tape and push/pop act on its head.
* each cell has a six-yao trace.
* `fen` builds the three-yao trigram spine from Yuan/Yao inputs.
* recursive structure expressions have only yao/root leaves.
* the catalogue has all 371 signature rows, while L0 has 12 executable clauses.
-/
theorem history_tape_structure_summary :
    (∀ s : YiState, stateTape s = s.history)
    ∧ (∀ s : YiState, stateTape (YiState.execute YiInstr.push s) = s.cur :: stateTape s)
    ∧ (∀ c : R8, (cellYuanTrace c).length = 6)
    ∧ (∀ y1 y2 y3 : Yuan,
        fenToTrigram (fenToSiXiang (fenToYi () y1) y2) y3 = ⟨y1, y2, y3⟩)
    ∧ (∀ e : StructureExpr, BuiltFromYao e)
    ∧ (∀ ops : CatalogueOperatorSeq, operatorSeqAct ops = .fen)
    ∧ (∀ m : MingSkeleton, nameAct m = .he)
    ∧ (∀ ops : CatalogueOperatorSeq, ∀ name : MingSkeleton, ∀ e : StructureExpr,
        CompleteMing name →
          operatorSeqAct ops = .fen
            ∧ nameAct name = .he
            ∧ WellFormedNamedStructure (namedByHe name (splitByOperators ops e)))
    ∧ (∀ x : RootOne, x = rootOne)
    ∧ Yuan = Yao
    ∧ qianKunYuanPoles = (Yao.yang, Yao.yin)
    ∧ qianKunTrigrams = (Trigram.heaven, Trigram.earth)
    ∧ (∀ l : VerticalLayer,
        layerYao Trigram.heaven l = Yao.yang ∧ layerYao Trigram.earth l = Yao.yin)
    ∧ qianKunJianReading = .betweenLayers
    ∧ qianKunJianReading ≠ .endpointInterval
    ∧ (∀ l : VerticalLayer, l ∈ qianKunJianLayers)
    ∧ (∀ l : VerticalLayer, ∀ s : SiXiang, ∀ y : Yuan,
        removeLayer l (fenAtLayer l s y) = s)
    ∧ fullOperatorSignatures.length = 371
    ∧ l0InstructionClauseKinds.length = 12 := by
  exact
    ⟨ stateTape_eq_history
    , push_writes_current_cell_to_tape
    , cellYuanTrace_length
    , fen_three_yuan_makes_trigram
    , structureExpr_built_from_yao
    , operator_sequences_are_fen
    , names_are_he
    , fen_he_expresses_structure
    , root_one_unique
    , yuan_is_yao
    , qianKunYuanPoles_eq
    , qianKunTrigrams_eq
    , fun l => ⟨qian_layers_are_yang l, kun_layers_are_yin l⟩
    , qianKunJianReading_is_between_layers
    , qianKunJianReading_not_endpoint_interval
    , qianKunJianLayers_complete
    , removeLayer_fenAtLayer
    , fullOperatorSignatures_length
    , l0InstructionClauseKinds_length
    ⟩

end SSBX.Foundation.Modern.HistoryTapeStructure
