/-
# QuantumRelativityPathQuotientBridge -- visible-key quotient classes

Companion:
`义理/路径商类候选 · Markov桥S5m.md`

This module advances S5l by constructing an actual Lean quotient over
two-step path witnesses, using visible-key equality as the relation:

1. it packages `TwoStepPathKeyEquivalent` as a `Setoid`;
2. it defines quotient classes for two-step path witnesses;
3. it lifts visible keys and key-level amplitudes to quotient classes;
4. it proves the two-route upper/lower quotient classes remain distinct and
   source/target quotient enumeration is complete in the toy process.

This is only a finite visible-key quotient-class construction.  It is not
proof-field path equality, not general all-path enumeration, not a path
integral, and not empirical closure.
-/
import SSBX.Foundation.Modern.QuantumRelativityFiniteKeyQuotientBridge

namespace SSBX.Foundation.Modern.QuantumRelativityPathQuotientBridge

open SSBX.Foundation.Modern.Quantum
open SSBX.Foundation.Modern.QuantumRelativityMarkovBridge
open SSBX.Foundation.Modern.QuantumRelativityTwoPathInterferenceBridge
open SSBX.Foundation.Modern.QuantumRelativityDiscreteActionBridge
open SSBX.Foundation.Modern.QuantumRelativityEndpointIndexedPathFamilyBridge
open SSBX.Foundation.Modern.QuantumRelativityTwoRouteEnumerationBridge
open SSBX.Foundation.Modern.QuantumRelativityPathIdentityBridge
open SSBX.Foundation.Modern.QuantumRelativityFiniteKeyQuotientBridge
open SSBX.Foundation.Modern.QuantumRelativityWenBoundary

/-! ## § 1 Quotient classes over visible keys -/

/-- Setoid generated by visible two-step path key equality. -/
def twoStepPathKeySetoid (P : FiniteProcess) :
    Setoid (TwoStepPathWitness P) where
  r := TwoStepPathKeyEquivalent
  iseqv := by
    refine ⟨?refl, ?symm, ?trans⟩
    · intro p
      exact two_step_path_key_equiv_refl p
    · intro p q h
      exact two_step_path_key_equiv_symm h
    · intro p q r hpq hqr
      exact two_step_path_key_equiv_trans hpq hqr

/-- Quotient of two-step path witnesses by visible-key equality. -/
def TwoStepPathKeyQuotient (P : FiniteProcess) : Type :=
  Quot (twoStepPathKeySetoid P)

/-- Send a two-step path witness to its visible-key quotient class. -/
def twoStepPathQuotientClass {P : FiniteProcess}
    (p : TwoStepPathWitness P) : TwoStepPathKeyQuotient P :=
  Quot.mk (twoStepPathKeySetoid P) p

/-- Same visible key implies same quotient class. -/
theorem same_key_implies_same_quotient_class {P : FiniteProcess}
    {p q : TwoStepPathWitness P}
    (h : TwoStepPathKeyEquivalent p q) :
    twoStepPathQuotientClass p = twoStepPathQuotientClass q :=
  Quot.sound h

/-- The visible key descends to the quotient. -/
def quotientVisibleKey {P : FiniteProcess} :
    TwoStepPathKeyQuotient P -> TwoStepPathKey P :=
  Quot.lift twoStepPathKey (by
    intro p q h
    exact h)

@[simp] theorem quotient_visible_key_mk {P : FiniteProcess}
    (p : TwoStepPathWitness P) :
    quotientVisibleKey (twoStepPathQuotientClass p) =
      twoStepPathKey p := by
  rfl

/-! ## § 2 Key-amplitude descent to quotient classes -/

/-- A key-amplitude candidate descends to quotient classes. -/
def quotientKeyAmplitude {P : FiniteProcess}
    (K : TwoStepKeyAmplitudeCandidate P) :
    TwoStepPathKeyQuotient P -> ℂ :=
  fun q => K.keyAmplitude (quotientVisibleKey q)

/-- A key-amplitude candidate keeps its Born-shaped boundary on quotient classes. -/
def quotientKeyBornWeight {P : FiniteProcess}
    (K : TwoStepKeyAmplitudeCandidate P)
    (q : TwoStepPathKeyQuotient P) : ℝ :=
  ampProb (quotientKeyAmplitude K q)

/--
If a path amplitude factors through visible keys, its value agrees with the
quotient key-amplitude on the path's quotient class.
-/
theorem quotient_key_amplitude_matches_path_of_factor
    {P : FiniteProcess}
    (A : TwoStepPathAmplitudeCandidate P)
    (K : TwoStepKeyAmplitudeCandidate P)
    (hFactor : PathAmplitudeFactorsThroughKey A K)
    (p : TwoStepPathWitness P) :
    quotientKeyAmplitude K (twoStepPathQuotientClass p) =
      A.twoStepAmplitude p := by
  rw [quotientKeyAmplitude, quotient_visible_key_mk, hFactor p]

/-! ## § 3 Two-route quotient witness -/

/-- Displayed source/target quotient classes in the two-route toy process. -/
def twoRouteSourceTargetQuotientEnumeration :
    List (TwoStepPathKeyQuotient twoRouteProcess) :=
  [twoStepPathQuotientClass twoRouteUpperPath,
    twoStepPathQuotientClass twoRouteLowerPath]

/-- The upper and lower displayed quotient classes are distinct. -/
theorem two_route_upper_lower_quotient_classes_distinct :
    twoStepPathQuotientClass twoRouteUpperPath ≠
      twoStepPathQuotientClass twoRouteLowerPath := by
  intro h
  have hKey :
      quotientVisibleKey (twoStepPathQuotientClass twoRouteUpperPath) =
        quotientVisibleKey (twoStepPathQuotientClass twoRouteLowerPath) :=
    congrArg quotientVisibleKey h
  simp at hKey
  exact two_route_upper_lower_keys_distinct hKey

/-- A source/target path with upper middle has the upper quotient class. -/
theorem two_route_source_target_upper_middle_quotient_class
    (p : TwoStepPathWitness twoRouteProcess)
    (hStart : p.start = TwoRouteState.source)
    (hMiddle : p.middle = TwoRouteState.upper)
    (hStop : p.stop = TwoRouteState.target) :
    twoStepPathQuotientClass p =
      twoStepPathQuotientClass twoRouteUpperPath := by
  exact same_key_implies_same_quotient_class
    (two_route_source_target_upper_middle_key p hStart hMiddle hStop)

/-- A source/target path with lower middle has the lower quotient class. -/
theorem two_route_source_target_lower_middle_quotient_class
    (p : TwoStepPathWitness twoRouteProcess)
    (hStart : p.start = TwoRouteState.source)
    (hMiddle : p.middle = TwoRouteState.lower)
    (hStop : p.stop = TwoRouteState.target) :
    twoStepPathQuotientClass p =
      twoStepPathQuotientClass twoRouteLowerPath := by
  exact same_key_implies_same_quotient_class
    (two_route_source_target_lower_middle_key p hStart hMiddle hStop)

/-- Every toy source/target two-step path has a quotient class in the displayed list. -/
theorem two_route_source_target_quotient_mem_enumeration
    (p : TwoStepPathWitness twoRouteProcess)
    (hStart : p.start = TwoRouteState.source)
    (hStop : p.stop = TwoRouteState.target) :
    twoStepPathQuotientClass p ∈
      twoRouteSourceTargetQuotientEnumeration := by
  rcases two_route_source_target_middle_upper_or_lower p hStart hStop with
    hUpper | hLower
  · rw [two_route_source_target_upper_middle_quotient_class
      p hStart hUpper hStop]
    simp [twoRouteSourceTargetQuotientEnumeration]
  · rw [two_route_source_target_lower_middle_quotient_class
      p hStart hLower hStop]
    simp [twoRouteSourceTargetQuotientEnumeration]

/-- The two-route quotient enumeration is complete for toy source/target paths. -/
def TwoRouteSourceTargetQuotientComplete : Prop :=
  ∀ p : TwoStepPathWitness twoRouteProcess,
    p.start = TwoRouteState.source ->
      p.stop = TwoRouteState.target ->
        twoStepPathQuotientClass p ∈
          twoRouteSourceTargetQuotientEnumeration

theorem two_route_source_target_quotient_complete :
    TwoRouteSourceTargetQuotientComplete := by
  intro p hStart hStop
  exact two_route_source_target_quotient_mem_enumeration p hStart hStop

/-! ## § 4 Public summary -/

/-- Public summary for S5m:
    visible-key equality is now packaged as a Lean quotient class construction;
    visible keys and key-level amplitudes descend to quotient classes; the
    two-route upper/lower quotient classes remain distinct; and toy
    source/target quotient enumeration is complete.  This proves only a finite
    visible-key quotient-class boundary, not proof-field path equality, general
    all-path enumeration, path integral, or empirical closure. -/
theorem path_quotient_bridge_summary :
    (∀ {P : FiniteProcess} {p q : TwoStepPathWitness P},
      TwoStepPathKeyEquivalent p q ->
        twoStepPathQuotientClass p = twoStepPathQuotientClass q)
    ∧ (∀ {P : FiniteProcess} (p : TwoStepPathWitness P),
      quotientVisibleKey (twoStepPathQuotientClass p) =
        twoStepPathKey p)
    ∧ (∀ {P : FiniteProcess}
        (A : TwoStepPathAmplitudeCandidate P)
        (K : TwoStepKeyAmplitudeCandidate P)
        (_hFactor : PathAmplitudeFactorsThroughKey A K)
        (p : TwoStepPathWitness P),
        quotientKeyAmplitude K (twoStepPathQuotientClass p) =
          A.twoStepAmplitude p)
    ∧ twoStepPathQuotientClass twoRouteUpperPath ≠
      twoStepPathQuotientClass twoRouteLowerPath
    ∧ TwoRouteSourceTargetQuotientComplete
    ∧ twoStepKeyBornWeight twoRouteKeyAmplitudeCandidate
      twoRouteSourceTargetKeyEnumeration = 0
    ∧ WenConstructiveCoverage := by
  rcases finite_key_quotient_bridge_summary with
    ⟨_hRefl, _hSymm, _hTrans, _hAmpCompat, _hDuplicate,
      _hKeyList, _hKeyCancel, hKeyBorn, _hDupBorn, _hKeyComplete,
      hCoverage⟩
  exact
    ⟨ same_key_implies_same_quotient_class
    , quotient_visible_key_mk
    , quotient_key_amplitude_matches_path_of_factor
    , two_route_upper_lower_quotient_classes_distinct
    , two_route_source_target_quotient_complete
    , hKeyBorn
    , hCoverage
    ⟩

end SSBX.Foundation.Modern.QuantumRelativityPathQuotientBridge
