/-
# R8AxisIndependence -- finite span checker for candidate axes

This module turns the `AxisAppropriate.independentFromPrior` certificate slot
from `R8ProjectionCalculus` into a finite R8-span condition.

It is intentionally small: independence is checked against the XOR span
generated by a finite list of prior masks. This is enough for the roadmap claim
"adding this axis is appropriate only when it is nonzero, independent, and
projectable".
-/

import SSBX.Foundation.Wen.R8ProjectionCalculus

namespace SSBX.Foundation.Wen.R8AxisIndependence

open SSBX.Foundation.Bagua.R8
open SSBX.Foundation.Wen.R8ProjectionCalculus

/-! ## Finite XOR span -/

/-- Finite XOR span generated by a list of R8 masks. -/
def spanMasks : List R8 -> List R8
  | [] => [R8.origin]
  | b :: rest =>
      let tail := spanMasks rest
      tail ++ tail.map (fun c => R8.xor b c)

@[simp] theorem spanMasks_nil :
    spanMasks [] = [R8.origin] := rfl

@[simp] theorem spanMasks_cons (b : R8) (rest : List R8) :
    spanMasks (b :: rest) =
      spanMasks rest ++ (spanMasks rest).map (fun c => R8.xor b c) := rfl

/-- The origin is always in the finite XOR span. -/
theorem origin_mem_spanMasks (prior : List R8) :
    R8.origin ∈ spanMasks prior := by
  induction prior with
  | nil =>
      simp [spanMasks]
  | cons b rest ih =>
      simp [spanMasks, ih]

/-- Independence from prior axes means the mask is not in their finite span. -/
def AxisIndependent (mask : R8) (prior : List R8) : Prop :=
  mask ∉ spanMasks prior

theorem axisIndependent_empty_iff (mask : R8) :
    AxisIndependent mask [] ↔ mask ≠ R8.origin := by
  simp [AxisIndependent, spanMasks]

theorem origin_not_independent (prior : List R8) :
    ¬ AxisIndependent R8.origin prior := by
  intro h
  exact h (origin_mem_spanMasks prior)

/-! ## Finite appropriateness certificate -/

/-- Candidate axis with an explicit finite prior basis. -/
structure AxisCandidate where
  mask : R8
  role : AxisRole
  prior : List R8
  projectable : Bool
  deriving Repr

/-- Convert a finite-span candidate to the older certificate-slot interface. -/
def AxisCandidate.toAxisSpec (a : AxisCandidate) : AxisSpec where
  mask := a.mask
  role := a.role
  independentFromPrior := AxisIndependent a.mask a.prior
  projectable := a.projectable

/-- Computable-frame version of axis appropriateness. -/
def AxisAppropriateBySpan (a : AxisCandidate) : Prop :=
  a.mask ≠ R8.origin
    ∧ AxisIndependent a.mask a.prior
    ∧ a.projectable = true

theorem axisAppropriateBySpan_to_AxisAppropriate (a : AxisCandidate) :
    AxisAppropriateBySpan a -> AxisAppropriate a.toAxisSpec := by
  intro h
  exact h

theorem axisAppropriateBySpan_has_nonzero_mask (a : AxisCandidate) :
    AxisAppropriateBySpan a -> a.mask ≠ R8.origin := fun h => h.1

theorem axisAppropriateBySpan_is_independent (a : AxisCandidate) :
    AxisAppropriateBySpan a -> AxisIndependent a.mask a.prior := fun h => h.2.1

theorem axisAppropriateBySpan_is_projectable (a : AxisCandidate) :
    AxisAppropriateBySpan a -> a.projectable = true := fun h => h.2.2

theorem dependent_axis_rejected (a : AxisCandidate) :
    a.mask ∈ spanMasks a.prior -> ¬ AxisAppropriateBySpan a := by
  intro hmem happ
  exact happ.2.1 hmem

theorem origin_axis_rejected (role : AxisRole) (prior : List R8) (projectable : Bool) :
    ¬ AxisAppropriateBySpan
      { mask := R8.origin, role := role, prior := prior, projectable := projectable } := by
  intro h
  exact h.1 rfl

theorem nonzero_empty_prior_appropriate
    (mask : R8) (role : AxisRole) (hmask : mask ≠ R8.origin) :
    AxisAppropriateBySpan
      { mask := mask, role := role, prior := [], projectable := true } := by
  exact ⟨hmask, (axisIndependent_empty_iff mask).2 hmask, rfl⟩

/-! ## Public summary -/

theorem r8_axis_independence_summary :
    (∀ prior : List R8, R8.origin ∈ spanMasks prior)
    ∧ (∀ prior : List R8, ¬ AxisIndependent R8.origin prior)
    ∧ (∀ mask : R8, AxisIndependent mask [] ↔ mask ≠ R8.origin)
    ∧ (∀ a : AxisCandidate,
        AxisAppropriateBySpan a -> AxisAppropriate a.toAxisSpec)
    ∧ (∀ a : AxisCandidate,
        a.mask ∈ spanMasks a.prior -> ¬ AxisAppropriateBySpan a) := by
  exact
    ⟨ origin_mem_spanMasks
    , origin_not_independent
    , axisIndependent_empty_iff
    , axisAppropriateBySpan_to_AxisAppropriate
    , dependent_axis_rejected
    ⟩

end SSBX.Foundation.Wen.R8AxisIndependence
